import Link from 'next/link';
import { Activity, ArrowLeft, BarChart3, CircleDollarSign, Gauge, ShieldCheck, Target, TrendingUp } from 'lucide-react';
import '../../company.css';
import './detail.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>['revenue','profit','cash','mrr','costs'].map(metricId=>({companyId,metricId})))}
const metrics:Record<string,{name:string;value:string;trend:string;target:string;variance:string;status:string;drivers:string[];forecast:string}>={revenue:{name:'Revenue',value:'€64,530',trend:'+18.6%',target:'€72,000',variance:'€7,470 to target',status:'ON TRACK',drivers:['AI Growth Suite expansion','Higher enterprise conversion','Pricing experiment #41'],forecast:'€72.8k projected next cycle'},profit:{name:'Net Profit',value:'€21,180',trend:'+12.4%',target:'€24,000',variance:'€2,820 to target',status:'ON TRACK',drivers:['Margin expansion','Cloud cost optimization','Controlled acquisition spend'],forecast:'€24.6k projected next cycle'},cash:{name:'Cash Reserve',value:'€28,640',trend:'8.4 months',target:'10 months',variance:'1.6 months below target',status:'WATCH',drivers:['Current operating burn','Approved experiments','Expected recurring revenue'],forecast:'9.1 months projected after current cycle'},mrr:{name:'Recurring Revenue',value:'€16,420',trend:'+21.8%',target:'€20,000',variance:'€3,580 to target',status:'ACCELERATING',drivers:['AI Growth Suite','Revenue Copilot pilots','Enterprise expansion'],forecast:'€20.7k projected next cycle'},costs:{name:'Operating Costs',value:'€43,350',trend:'+4.2%',target:'≤ €42,000',variance:'€1,350 above target',status:'OPTIMIZING',drivers:['Infrastructure +6.2%','Marketing experiments','Automation savings'],forecast:'€41.8k projected after optimization'}};
export default function FinanceDetail({params}:{params:{companyId:string;metricId:string}}){const p=params;const m=metrics[p.metricId]||metrics.revenue;return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href={`/company/${p.companyId}`}>← <span>Company workspace</span></Link><div className="companyIdentity"><span>FINANCE</span><strong>{m.name}</strong><small>{m.status}</small><i><em/> Simulation</i></div><div className="companySafety"><ShieldCheck size={15}/><span>Simulation mode<br/><b>Financial actions gated</b></span></div></aside><section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">FINANCE DETAIL / {m.status}</span><h1>{m.name}</h1><p>Financial intelligence, variance analysis and autonomous forecasting.</p></div><Link href={`/company/${p.companyId}`} className="detailBack"><ArrowLeft size={15}/> Back</Link></header><section className="financeHero"><div><div className="detailIcon"><CircleDollarSign size={26}/></div><span>CURRENT FINANCIAL SIGNAL</span><h2>{m.value}</h2><b className="detailState"><i/>{m.status} · {m.trend}</b></div><div className="financeScore"><strong>{m.trend}</strong><span>TREND</span></div></section><div className="detailStats"><DetailStat icon={<CircleDollarSign size={17}/>} label="Current" value={m.value} detail={m.name}/><DetailStat icon={<Target size={17}/>} label="Target" value={m.target} detail="Operating objective"/><DetailStat icon={<Activity size={17}/>} label="Variance" value={m.variance} detail="Against target"/><DetailStat icon={<TrendingUp size={17}/>} label="Forecast" value={m.forecast} detail="Autonomous projection"/></div><div className="detailGrid"><section className="detailPanel"><Head icon={<BarChart3 size={16}/>} title="Target progress"/><div className="financeBar"><i style={{width:m.status==='WATCH'?'72%':'86%'}}/></div><p>Finance Agent evaluates the current trajectory and updates the forecast after each execution cycle.</p></section><section className="detailPanel"><Head icon={<Gauge size={16}/>} title="Key drivers"/><div className="driverList">{m.drivers.map((d,i)=><div key={d}><b>{String(i+1).padStart(2,'0')}</b><span>{d}</span></div>)}</div></section><section className="detailPanel wide"><Head icon={<ShieldCheck size={16}/>} title="Decision boundary"/><h3>Financial execution remains gated by explicit approval.</h3><p>The AI can forecast, compare scenarios and recommend allocation, but external financial side effects remain blocked until the operator enables the required control.</p></section></div><footer>AI Company OS · FINANCE → FORECAST → ALLOCATION → CONTROL → RESULT</footer></section></main>}
function DetailStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="detailStat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="detailHead">{icon}<h3>{title}</h3></div>}
