import Link from 'next/link';
import { Activity, ArrowLeft, Bot, CircleDollarSign, HeartPulse, ShieldCheck, Target, Users } from 'lucide-react';
import '../../company.css';
import './detail.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>['acme','nova','vertex','orbit'].map(customerId=>({companyId,customerId})))}
const customers:Record<string,{name:string;segment:string;stage:string;arr:string;health:string;last:string;agent:string;trend:string;risk:string;actions:string[]}>=
{'acme':{name:'Acme Digital',segment:'Enterprise',stage:'EXPANSION',arr:'€38,400',health:'96%',last:'2h ago',agent:'Sales Agent',trend:'+18.2% ARR',risk:'LOW',actions:['Review expansion proposal','Schedule executive onboarding','Monitor seat adoption']},'nova':{name:'Nova Commerce',segment:'Growth',stage:'ACTIVE',arr:'€14,880',health:'91%',last:'5h ago',agent:'Research Agent',trend:'+11.6% ARR',risk:'LOW',actions:['Analyze usage signal','Recommend retention offer','Update account memory']},'vertex':{name:'Vertex Labs',segment:'Enterprise',stage:'AT RISK',arr:'€9,600',health:'72%',last:'1d ago',agent:'Sales Agent',trend:'-4.1% ARR',risk:'MEDIUM',actions:['Investigate usage drop','Trigger success workflow','Escalate renewal risk']},'orbit':{name:'Orbit Systems',segment:'SMB',stage:'NEW',arr:'€4,320',health:'88%',last:'3h ago',agent:'Research Agent',trend:'+24.8% ARR',risk:'LOW',actions:['Complete onboarding','Validate ICP fit','Prepare expansion signal']}};
export default function CustomerDetail({params}:{params:{companyId:string;customerId:string}}){const p=params;const c=customers[p.customerId]||customers.acme;return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href={`/company/${p.companyId}`}>← <span>Company workspace</span></Link><div className="companyIdentity"><span>CUSTOMER</span><strong>{c.name}</strong><small>{c.stage}</small><i><em/> Monitored</i></div><div className="companySafety"><ShieldCheck size={15}/><span>Simulation mode<br/><b>Actions gated</b></span></div></aside><section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">CUSTOMER DETAIL / {c.stage}</span><h1>{c.name}</h1><p>{c.segment} account · {c.last} since last interaction.</p></div><Link href={`/company/${p.companyId}`} className="detailBack"><ArrowLeft size={15}/> Back</Link></header><section className="customerHero"><div><div className="detailIcon"><Users size={26}/></div><span>{c.segment} · {c.stage}</span><h2>Account health and revenue relationship</h2><b className="detailState"><i/>{c.risk} RISK</b></div><div className="healthScore"><strong>{c.health}</strong><span>HEALTH</span></div></section><div className="detailStats"><DetailStat icon={<CircleDollarSign size={17}/>} label="ARR" value={c.arr} detail="Annual recurring revenue"/><DetailStat icon={<HeartPulse size={17}/>} label="Health" value={c.health} detail="Account health"/><DetailStat icon={<Activity size={17}/>} label="Trend" value={c.trend} detail="Revenue trajectory"/><DetailStat icon={<Bot size={17}/>} label="Agent" value={c.agent.replace(' Agent','')} detail="Account owner"/></div><div className="detailGrid"><section className="detailPanel"><Head icon={<Target size={16}/>} title="Lifecycle"/><div className="lifecycle"><span>ACQUIRED</span><b>→</b><span>ACTIVE</span><b>→</b><strong>{c.stage}</strong></div><p>The customer signal layer continuously evaluates value, engagement, expansion and churn risk.</p></section><section className="detailPanel"><Head icon={<Bot size={16}/>} title="Assigned AI agent"/><h3>{c.agent}</h3><p>Responsible for interpreting account signals and preparing the next approved action.</p></section><section className="detailPanel wide"><Head icon={<Activity size={16}/>} title="Open customer actions"/><div className="missionTasks">{c.actions.map((a,i)=><div key={a}><b>{String(i+1).padStart(2,'0')}</b><span>{a}</span><strong>{i===0?'NEXT':'QUEUED'}</strong></div>)}</div></section></div><footer>AI Company OS · CUSTOMER → HEALTH → VALUE → RETENTION → EXPANSION</footer></section></main>}
function DetailStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="detailStat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="detailHead">{icon}<h3>{title}</h3></div>}
