import Link from 'next/link';
import { Activity, ArrowLeft, Bot, CheckCircle2, GitBranch, ShieldCheck, Target, Users, Zap } from 'lucide-react';
import '../../company.css';
import './mission-detail.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>['growth-product','retention','cost','enterprise'].map(missionId=>({companyId,missionId})))}
const missions:Record<string,{title:string;objective:string;progress:number;status:string;owner:string;agents:string[];tasks:string[];risk:string;result:string}>={
'growth-product':{title:'Launch next recurring-revenue product',objective:'Turn validated demand into a scalable recurring offer.',progress:78,status:'EXECUTING',owner:'CEO Agent',agents:['CEO Agent','Research Agent','Product Agent','Sales Agent','CFO Agent'],tasks:['Validate pricing experiment #41','Prepare landing page release','Publish experiment result'],risk:'LOW',result:'Expected recurring revenue uplift +€4,820/month'},retention:{title:'Improve customer retention',objective:'Reduce churn by improving onboarding and expansion signals.',progress:62,status:'RESEARCH',owner:'Research Agent',agents:['Research Agent','Sales Agent','Product Agent'],tasks:['Analyze high-intent segments','Run retention experiment'],risk:'MEDIUM',result:'Target: 18% churn reduction'},cost:{title:'Reduce operating cost',objective:'Protect margin without slowing product execution.',progress:41,status:'PLANNING',owner:'CFO Agent',agents:['CFO Agent','CEO Agent','Product Agent'],tasks:['Review weekly cash allocation','Optimize cloud infrastructure'],risk:'LOW',result:'Target: 8% operating cost reduction'},enterprise:{title:'Expand enterprise segment',objective:'Validate enterprise demand and build a repeatable sales motion.',progress:28,status:'BACKLOG',owner:'Sales Agent',agents:['Sales Agent','Research Agent'],tasks:['Validate enterprise ICP','Prepare outbound experiment'],risk:'MEDIUM',result:'Target: 12 qualified enterprise opportunities'}};
export default function MissionDetail({params}:{params:{companyId:string;missionId:string}}){const p=params;const m=missions[p.missionId]||missions['growth-product'];return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href={`/company/${p.companyId}`}>← <span>Company workspace</span></Link><div className="companyIdentity"><span>MISSION</span><strong>{m.title}</strong><small>{m.status}</small><i><em/> Controlled</i></div><div className="companySafety"><ShieldCheck size={15}/><span>Simulation mode<br/><b>Execution gated</b></span></div></aside><section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">MISSION DETAIL / {m.status}</span><h1>{m.title}</h1><p>{m.objective}</p></div><Link href={`/company/${p.companyId}`} className="detailBack"><ArrowLeft size={15}/> Back</Link></header><section className="missionDetailHero"><div><div className="detailIcon"><Target size={26}/></div><span>OWNER · {m.owner}</span><h2>{m.objective}</h2><b className="detailState"><i/>{m.status}</b></div><div className="missionScore"><strong>{m.progress}%</strong><span>EXECUTION</span></div></section><div className="detailStats"><DetailStat icon={<Target size={17}/>} label="Progress" value={`${m.progress}%`} detail="Mission execution"/><DetailStat icon={<Users size={17}/>} label="Agents" value={String(m.agents.length)} detail="Assigned workforce"/><DetailStat icon={<Zap size={17}/>} label="Tasks" value={String(m.tasks.length)} detail="Tracked actions"/><DetailStat icon={<ShieldCheck size={17}/>} label="Risk" value={m.risk} detail="Current control level"/></div><div className="detailGrid"><section className="detailPanel"><Head icon={<Activity size={16}/>} title="Execution status"/><div className="detailProgress"><i style={{width:`${m.progress}%`}}/></div><p>{m.result}</p><small>{m.progress}% of the mission plan is currently complete.</small></section><section className="detailPanel"><Head icon={<Bot size={16}/>} title="Assigned agents"/><div className="detailChips">{m.agents.map(a=><span key={a}>{a}</span>)}</div></section><section className="detailPanel wide"><Head icon={<GitBranch size={16}/>} title="Mission task graph"/><div className="missionTasks">{m.tasks.map((t,i)=><div key={t}><b>{String(i+1).padStart(2,'0')}</b><span>{t}</span><strong>{i===0?'EXECUTING':i===1?'PLANNING':'WAITING'}</strong></div>)}</div></section><section className="detailPanel wide"><Head icon={<CheckCircle2 size={16}/>} title="Expected result"/><h3>{m.result}</h3><p>The autonomous loop will evaluate the result, update company memory and decide the next mission step.</p></section></div><footer>AI Company OS · MISSION → TASKS → AGENTS → TOOLS → RESULTS → LEARNING</footer></section></main>}
function DetailStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="detailStat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="detailHead">{icon}<h3>{title}</h3></div>}
