'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Bot, BrainCircuit, CheckCircle2, CircleDollarSign, Network, Plus, ShieldCheck, Target, Users, Zap } from 'lucide-react'
import './module.css'

type Tenant = { id:string; name:string; sector:string; market:string; operatingModel:string; objective:string; health:number; agents:string[]; modules:string[]; portal:string; createdAt:string; missions?: {id:string;name:string;status:string}[]; tasks?: {id:string;name:string;status:string}[]; knowledge?: string[] }
const agentNames: Record<string,string> = {ceo:'CEO',research:'Research',product:'Product',sales:'Sales',cfo:'Finance'}
const moduleInfo: Record<string,{title:string;icon:any;description:string}> = {
  agents:{title:'AI Workforce',icon:Bot,description:'Manage the autonomous workforce assigned to this company.'},
  missions:{title:'Missions',icon:Target,description:'Define strategic missions and track execution.'},
  tasks:{title:'Tasks',icon:Zap,description:'Control the execution queue generated by missions.'},
  finance:{title:'Finance',icon:CircleDollarSign,description:'Monitor financial performance and operating economics.'},
  knowledge:{title:'Knowledge',icon:BrainCircuit,description:'Build the company memory and knowledge layer.'},
  operations:{title:'Operations',icon:Network,description:'Monitor the autonomous operating loop and integrations.'},
  security:{title:'Security',icon:ShieldCheck,description:'Review tenant isolation, policies and security controls.'},
  portal:{title:'Client Portal',icon:Users,description:'Open the client-facing operating view for this company.'},
}

export default function TenantModule(){
  const [tenant,setTenant]=useState<Tenant|null>(null); const [value,setValue]=useState(''); const [saved,setSaved]=useState(false)
  const params=typeof window!=='undefined'?new URLSearchParams(window.location.search):null; const tenantId=params?.get('tenant')||''; const module=params?.get('module')||'agents'; const info=moduleInfo[module]||moduleInfo.agents; const Icon=info.icon
  useEffect(()=>{try{const list=JSON.parse(localStorage.getItem('ai-company-os-tenants')||'[]');setTenant(list.find((x:Tenant)=>x.id===tenantId)||null)}catch{setTenant(null)}},[tenantId])
  const items=useMemo(()=>module==='missions'?(tenant?.missions||[]):module==='tasks'?(tenant?.tasks||[]):module==='knowledge'?(tenant?.knowledge||[]):[],[tenant,module])
  function addItem(){if(!tenant||!value.trim())return;const list=JSON.parse(localStorage.getItem('ai-company-os-tenants')||'[]');const i=list.findIndex((x:Tenant)=>x.id===tenant.id);if(i<0)return;const next={...list[i]};if(module==='missions')next.missions=[...(next.missions||[]),{id:Date.now().toString(36),name:value.trim(),status:'planned'}];if(module==='tasks')next.tasks=[...(next.tasks||[]),{id:Date.now().toString(36),name:value.trim(),status:'queued'}];if(module==='knowledge')next.knowledge=[...(next.knowledge||[]),value.trim()];list[i]=next;localStorage.setItem('ai-company-os-tenants',JSON.stringify(list));setTenant(next);setValue('');setSaved(true);setTimeout(()=>setSaved(false),1800)}
  if(!tenant)return <main className="modulePage"><div className="moduleEmpty">Tenant not found.<Link href="/master">Back to Master</Link></div></main>
  if(module==='portal')return <main className="modulePage"><div className="moduleTop"><Link href={`/master/tenant?id=${encodeURIComponent(tenant.id)}`}><ArrowLeft size={15}/> Tenant Control Center</Link></div><section className="moduleHero"><Icon size={24}/><span>CLIENT PORTAL</span><h1>{tenant.name}</h1><p>{tenant.objective}</p><Link className="primary" href={`/portal?tenant=${encodeURIComponent(tenant.id)}`}>Open Client Portal</Link></section></main>
  return <main className="modulePage"><div className="moduleTop"><Link href={`/master/tenant?id=${encodeURIComponent(tenant.id)}`}><ArrowLeft size={15}/> {tenant.name}</Link><span>{tenant.sector} · {tenant.market}</span></div><section className="moduleHero"><Icon size={24}/><span>MODULE</span><h1>{info.title}</h1><p>{info.description}</p></section>
  {module==='agents'&&<section className="moduleGrid">{tenant.agents.map(id=><article className="moduleCard" key={id}><Bot size={19}/><h3>{agentNames[id]||id}</h3><strong>ACTIVE</strong><p>Core autonomous agent · ready for missions and tasks.</p></article>)}</section>}
  {module==='finance'&&<section className="metricGrid"><div><span>Revenue</span><strong>€0</strong><p>Awaiting first commercial activity</p></div><div><span>Profit</span><strong>€0</strong><p>No operating results recorded</p></div><div><span>Health</span><strong>{tenant.health}%</strong><p>Provisioned system health</p></div></section>}
  {module==='operations'&&<section className="moduleGrid">{['Autonomous loop','Task pipeline','Integrations'].map(x=><article className="moduleCard" key={x}><CheckCircle2 size={19}/><h3>{x}</h3><strong>READY</strong><p>Configuration is provisioned and ready for activation.</p></article>)}</section>}
  {module==='security'&&<section className="moduleGrid">{['Tenant isolation','Access control','Audit trail'].map(x=><article className="moduleCard" key={x}><ShieldCheck size={19}/><h3>{x}</h3><strong>PROTECTED</strong><p>Baseline control initialized for this tenant.</p></article>)}</section>}
  {(module==='missions'||module==='tasks'||module==='knowledge')&&<section className="listPanel"><div className="addRow"><input value={value} onChange={e=>setValue(e.target.value)} placeholder={module==='knowledge'?'Add knowledge item...':`Add ${module.slice(0,-1)}...`} /><button onClick={addItem}><Plus size={16}/> Add</button></div>{saved&&<div className="saved">Saved locally</div>}{items.length===0?<p className="emptyText">Nothing configured yet. Add the first item above.</p>:items.map((item:any,i)=><div className="listItem" key={i}><span>{typeof item==='string'?item:item.name}</span><small>{typeof item==='string'?'MEMORY':item.status.toUpperCase()}</small></div>)}</section>}
  </main>
}
