import Link from 'next/link';
import { Activity, ArrowLeft, BrainCircuit, Bot, CheckCircle2, ChartNoAxesCombined, ShieldCheck, Sparkles, Target } from 'lucide-react';
import '../../../company.css';
import './detail.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>['expansion','growth','retention','risk'].map(insightId=>({companyId,insightId})))}
const insights:Record<string,{title:string;type:string;confidence:string;impact:string;evidence:string[];agents:string[];action:string;decision:string}>={
expansion:{title:'Three-seat accounts have 2.4× expansion probability',type:'OPPORTUNITY',confidence:'92%',impact:'HIGH',evidence:['Accounts with 3+ seats expand faster','Enterprise onboarding calls correlate with higher retention','Current cohort shows stronger product adoption'],agents:['Research Agent','Sales Agent','CEO Agent'],action:'Prioritize expansion motion for high-intent multi-seat accounts.',decision:'CEO Agent delegated pricing and expansion validation to Product and Sales.'},
growth:{title:'Demand is accelerating in two customer segments',type:'GROWTH SIGNAL',confidence:'86%',impact:'HIGH',evidence:['Qualified pipeline increased 17.3%','Experiment #41 is outperforming baseline','Two segments show repeated positive demand signals'],agents:['Research Agent','Product Agent','Sales Agent'],action:'Increase experiment capacity while maintaining the margin gate.',decision:'Product Agent started experiment #41 after evaluation gate approval.'},
retention:{title:'Onboarding quality is the strongest retention lever',type:'RETENTION',confidence:'84%',impact:'MEDIUM',evidence:['Onboarding calls improve early activation','Customers with completed onboarding expand more often','Churn risk concentrates in low-engagement accounts'],agents:['Research Agent','Sales Agent'],action:'Trigger proactive onboarding workflows for at-risk accounts.',decision:'Sales Agent prepared a retention experiment for the next cycle.'},
risk:{title:'Infrastructure cost increased after the latest release',type:'RISK',confidence:'79%',impact:'MEDIUM',evidence:['Cloud cost rose 6.2%','New workload pattern is resource intensive','Optimization can recover part of the margin impact'],agents:['CFO Agent','Product Agent'],action:'Run cost optimization before approving additional workload expansion.',decision:'CFO Agent flagged a controlled optimization mission.'}};
export default function IntelligenceDetail({params}:{params:{companyId:string;insightId:string}}){const p=params;const x=insights[p.insightId]||insights.expansion;return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href={`/company/${p.companyId}`}>← <span>Company workspace</span></Link><div className="companyIdentity"><span>INTELLIGENCE</span><strong>{x.type}</strong><small>{x.impact} IMPACT</small><i><em/> Evaluated</i></div><div className="companySafety"><ShieldCheck size={15}/><span>Decision engine<br/><b>Human approval gated</b></span></div></aside><section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">INTELLIGENCE DETAIL / {x.type}</span><h1>{x.title}</h1><p>Evidence-backed signal generated and evaluated by the autonomous company loop.</p></div><Link href={`/company/${p.companyId}`} className="detailBack"><ArrowLeft size={15}/> Back</Link></header><section className="intelHero"><div><div className="detailIcon"><BrainCircuit size={26}/></div><span>{x.type} · {x.impact} IMPACT</span><h2>{x.action}</h2><b className="detailState"><i/>{x.confidence} CONFIDENCE</b></div><div className="confidenceScore"><strong>{x.confidence}</strong><span>CONFIDENCE</span></div></section><div className="detailStats"><DetailStat icon={<BrainCircuit size={17}/>} label="Confidence" value={x.confidence} detail="Model evaluation"/><DetailStat icon={<ChartNoAxesCombined size={17}/>} label="Impact" value={x.impact} detail="Business effect"/><DetailStat icon={<Bot size={17}/>} label="Agents" value={String(x.agents.length)} detail="Connected workforce"/><DetailStat icon={<Target size={17}/>} label="State" value="EVALUATED" detail="Decision ready"/></div><div className="detailGrid"><section className="detailPanel"><Head icon={<Sparkles size={16}/>} title="Recommended action"/><h3>{x.action}</h3><p>The recommendation is available to the decision engine but remains subject to the company approval policy.</p></section><section className="detailPanel"><Head icon={<Bot size={16}/>} title="Contributing agents"/><div className="detailChips">{x.agents.map(a=><span key={a}>{a}</span>)}</div></section><section className="detailPanel wide"><Head icon={<Activity size={16}/>} title="Evidence"/><div className="evidenceList">{x.evidence.map((e,i)=><div key={e}><b>{String(i+1).padStart(2,'0')}</b><span>{e}</span><strong>SUPPORTED</strong></div>)}</div></section><section className="detailPanel wide"><Head icon={<CheckCircle2 size={16}/>} title="Decision history"/><h3>{x.decision}</h3><p>The intelligence layer records the signal, reasoning, decision and result so future cycles can learn from the outcome.</p></section></div><footer>AI Company OS · SIGNAL → EVIDENCE → DECISION → ACTION → RESULT → LEARNING</footer></section></main>}
function DetailStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="detailStat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="detailHead">{icon}<h3>{title}</h3></div>}
