import Link from 'next/link';
import '../knowledge-detail.css';

const items: Record<string,{title:string;type:string;confidence:string;summary:string;evidence:string[];agents:string[];action:string}>={
  pricing:{title:'Pricing Experiment Memory',type:'Decision Memory',confidence:'94%',summary:'The last validated pricing experiment improved conversion without materially reducing margin.',evidence:['Conversion improved 11.4% in experiment #38','Enterprise accounts responded best to annual plans','Margin remained above the current safety threshold'],agents:['Research Agent','Product Agent','CFO Agent'],action:'Use this memory as a constraint for the next pricing experiment.'},
  onboarding:{title:'Enterprise Onboarding Pattern',type:'Customer Memory',confidence:'91%',summary:'Enterprise customers expand faster when the first onboarding interaction is assisted by an agent.',evidence:['Accounts with onboarding calls show higher expansion probability','Three-seat accounts are the strongest expansion cohort','Retention signals improve after guided setup'],agents:['Research Agent','Sales Agent'],action:'Prioritize assisted onboarding for high-value accounts.'},
  infrastructure:{title:'Infrastructure Cost Signal',type:'Operational Memory',confidence:'88%',summary:'Infrastructure cost increased after the latest release and requires monitoring before the next scale event.',evidence:['Infrastructure cost rose 6.2% after the last release','Execution volume increased during the same cycle','Current margin remains within policy'],agents:['CFO Agent','Product Agent'],action:'Review cost per execution before increasing workload capacity.'},
  promotion:{title:'Promotion Window',type:'Growth Memory',confidence:'86%',summary:'The strongest observed promotion window remains between 14:00 and 16:00.',evidence:['Multiple promotion cycles peaked in this interval','Conversion was consistently above baseline','Signal has remained stable across recent cycles'],agents:['Research Agent','Sales Agent'],action:'Schedule the next controlled growth experiment inside this window.'}
};
export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>Object.keys(items).map(knowledgeId=>({companyId,knowledgeId})))}
export default function KnowledgeDetail({params}:{params:{companyId:string;knowledgeId:string}}){const item=items[params.knowledgeId]||items.pricing;return <main className="knowledgeDetail"><Link href={`/company/${params.companyId}?view=knowledge`} className="backLink">← Back to Knowledge</Link><header><span>COMPANY KNOWLEDGE / {item.type.toUpperCase()}</span><h1>{item.title}</h1><p>{item.summary}</p></header><section className="knowledgeGrid"><article><small>CONFIDENCE</small><strong>{item.confidence}</strong></article><article><small>MEMORY STATUS</small><strong>ACTIVE</strong></article><article><small>CONNECTED AGENTS</small><strong>{item.agents.length}</strong></article></section><section className="knowledgePanel"><h2>Evidence</h2>{item.evidence.map(x=><div className="knowledgeRow" key={x}><b>✓</b><span>{x}</span></div>)}</section><section className="knowledgePanel"><h2>Agents using this memory</h2><div className="agentChips">{item.agents.map(x=><span key={x}>{x}</span>)}</div></section><section className="knowledgeAction"><small>RECOMMENDED ACTION</small><h2>{item.action}</h2></section></main>}