import Link from 'next/link';
import { Activity, ArrowLeft, Bot, CheckCircle2, CircleDollarSign, Gauge, ShieldCheck, Target, Users } from 'lucide-react';
import '../../../company.css';
import './detail.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>['ai-growth-suite','revenue-copilot','retention-engine'].map(productId=>({companyId,productId})))}
const products:Record<string,{name:string;type:string;status:string;mrr:string;customers:string;growth:string;objective:string;conversion:string;retention:string;margin:string;agents:string[];tasks:string[];risk:string}>={
'ai-growth-suite':{name:'AI Growth Suite',type:'Recurring SaaS',status:'LIVE',mrr:'€9,840',customers:'142',growth:'+22.4%',objective:'Scale the core recurring-revenue engine while protecting margin.',conversion:'8.7%',retention:'94.2%',margin:'68%',agents:['Product Agent','Sales Agent','CFO Agent'],tasks:['Review pricing experiment #41','Launch onboarding variant B','Monitor expansion cohort'],risk:'LOW'},
'revenue-copilot':{name:'Revenue Copilot',type:'AI Product',status:'EXPERIMENT',mrr:'€2,180',customers:'31',growth:'+€1.7k expected',objective:'Validate a higher-value AI-assisted revenue workflow.',conversion:'6.2%',retention:'89.4%',margin:'61%',agents:['Product Agent','Research Agent','Sales Agent'],tasks:['Complete ICP validation','Run pricing test','Publish experiment result'],risk:'MEDIUM'},
'retention-engine':{name:'Retention Engine',type:'AI Automation',status:'BUILDING',mrr:'—',customers:'Pilot',growth:'64% validation',objective:'Reduce churn through proactive customer health signals.',conversion:'Pilot',retention:'Target 18% churn reduction',margin:'Projected 72%',agents:['Product Agent','Research Agent','CFO Agent'],tasks:['Validate churn model','Connect customer signals','Run pilot cohort'],risk:'MEDIUM'}};
export default function ProductDetail({params}:{params:{companyId:string;productId:string}}){const p=params;const x=products[p.productId]||products['ai-growth-suite'];return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href={`/company/${p.companyId}`}>← <span>Company workspace</span></Link><div className="companyIdentity"><span>PRODUCT</span><strong>{x.name}</strong><small>{x.status}</small><i><em/> Controlled</i></div><div className="companySafety"><ShieldCheck size={15}/><span>Simulation mode<br/><b>Execution gated</b></span></div></aside><section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">PRODUCT DETAIL / {x.status}</span><h1>{x.name}</h1><p>{x.objective}</p></div><Link href={`/company/${p.companyId}`} className="detailBack"><ArrowLeft size={15}/> Back</Link></header><section className="productHero"><div><div className="detailIcon"><Gauge size={26}/></div><span>{x.type} · {x.status}</span><h2>{x.objective}</h2><b className="detailState"><i/>{x.status}</b></div><div className="productScore"><strong>{x.growth}</strong><span>GROWTH</span></div></section><div className="detailStats"><DetailStat icon={<CircleDollarSign size={17}/>} label="MRR" value={x.mrr} detail="Recurring revenue"/><DetailStat icon={<Users size={17}/>} label="Customers" value={x.customers} detail="Active accounts"/><DetailStat icon={<Activity size={17}/>} label="Retention" value={x.retention} detail="Current cohort"/><DetailStat icon={<ShieldCheck size={17}/>} label="Risk" value={x.risk} detail="Control level"/></div><div className="detailGrid"><section className="detailPanel"><Head icon={<Target size={16}/>} title="Product objective"/><h3>{x.objective}</h3><p>The product is evaluated continuously by the autonomous loop against revenue, customer and margin signals.</p></section><section className="detailPanel"><Head icon={<CircleDollarSign size={16}/>} title="Unit economics"/><div className="metricLine"><span>Conversion</span><b>{x.conversion}</b></div><div className="metricLine"><span>Gross margin</span><b>{x.margin}</b></div></section><section className="detailPanel"><Head icon={<Bot size={16}/>} title="Assigned agents"/><div className="detailChips">{x.agents.map(a=><span key={a}>{a}</span>)}</div></section><section className="detailPanel wide"><Head icon={<CheckCircle2 size={16}/>} title="Product execution"/><div className="missionTasks">{x.tasks.map((t,i)=><div key={t}><b>{String(i+1).padStart(2,'0')}</b><span>{t}</span><strong>{i===0?'EXECUTING':i===1?'PLANNING':'WAITING'}</strong></div>)}</div></section></div><footer>AI Company OS · PRODUCT → EXPERIMENT → CUSTOMERS → REVENUE → LEARNING</footer></section></main>}
function DetailStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="detailStat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="detailHead">{icon}<h3>{title}</h3></div>}
