'use client'

import { useState, type ReactNode } from 'react'
import { Activity, Bot, BrainCircuit, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Database, Megaphone, Package, PlugZap, Settings, ShieldCheck, Target, Users, Wallet, WalletCards, Zap } from 'lucide-react'
import styles from '../../app/company/[companyId]/CompanyRuntimeWorkspace.module.css'
import { formatMoney } from '../../lib/business-metrics'
import { useCompanyRuntime } from '../../app/company/[companyId]/CompanyRuntimeContext'
import type { CompanyView } from './CompanyNavigation'
import ApprovalsModule from './CompanyApprovals'

type Company = { name: string; type: string; revenue: string; profit: string; health: string; agents: number; missions: number; objective: string }

type Props = { company: Company; view: CompanyView; setView: (view: CompanyView) => void }

export default function CompanyRuntimeContent({ company, view, setView }: Props) {
  const [action, setAction] = useState<{title:string; body:string} | null>(null)
  const open = (title:string, body:string) => setAction({title, body})
  return <>
    {view === 'Dashboard' ? <Dashboard company={company} setView={setView}/> : <Module company={company} view={view} open={open}/>}
    {action && <ActionModal title={action.title} body={action.body} onClose={() => setAction(null)}/>}
  </>
}

function Dashboard({ company, setView }: { company: Company; setView: (v: CompanyView) => void }) {
  const { running, setRunning, metrics, progress, counts, metricEvent, lastAction } = useCompanyRuntime()
  return <>
    <PageHead eyebrow="COMPANY OVERVIEW" title="Dashboard" text={<>Operational intelligence for <b>{company.name}</b>.</>}><span className={styles.live}><i/>LIVE</span><button className={styles.secondary} onClick={() => setView('Missions')}><Target size={15}/>View missions</button><button className={styles.primary} onClick={() => setRunning(!running)}><Activity size={15}/>{running ? 'AI running' : 'AI paused'}</button></PageHead>
    <div className={styles.kpis}>
      <Kpi label="Revenue" value={formatMoney(metrics.revenue)} change="Runtime result" icon={<CircleDollarSign/>}/><Kpi label="Conversion Rate" value={`${metrics.conversionRate}%`} change={`${metrics.conversionDelta >= 0 ? '+' : ''}${metrics.conversionDelta}% live`} icon={<Target/>}/><Kpi label="AI Workforce" value={String(company.agents)} change={`${counts.executing} executing`} icon={<Bot/>}/><Kpi label="Active Missions" value={String(company.missions)} change={`${progress}% execution`} icon={<Zap/>}/><Kpi label="Company Health" value={company.health} change="Operational" icon={<Activity/>}/>
    </div>
    <div className={styles.grid}><section className={styles.panel}><Head title="COMPANY PERFORMANCE" text="Revenue & conversion" action="Intelligence" onClick={() => setView('Intelligence')}/><MetricChart history={metrics.history}/></section><section className={styles.panel}><Head title="AI WORKFORCE" text="Agents at work" action="View all" onClick={() => setView('Agents')}/><Agent n="AI Director" r="Orchestration & strategy" s="Working" v="98%"/><Agent n="Growth Agent" r="Marketing & acquisition" s="Working" v="91%"/><Agent n="Sales Agent" r="Pipeline & conversion" s="Working" v="87%"/><Agent n="Analyst Agent" r="Intelligence & insight" s="Idle" v="76%"/></section></div>
    <div className={styles.grid2}><section className={styles.panel}><Head title="COMMERCIAL FUNNEL" text="Live business movement" action="Marketing" onClick={() => setView('Marketing')}/><Funnel metrics={metrics}/></section><section className={styles.panel}><Head title="RECENT ACTIVITY" text="What is happening now" action="Intelligence" onClick={() => setView('Intelligence')}/><ActivityRow text={metricEvent} status="LIVE"/><ActivityRow text={lastAction} status="RUNTIME"/><ActivityRow text={`${metrics.conversions} conversions from ${metrics.opportunities} opportunities`} status="METRIC"/><ActivityRow text={`${counts.completed} tasks completed by runtime`} status="DONE"/></section></div>
    <div className={styles.director}><div><small>AI DIRECTOR</small><b>{running ? 'Autonomous operation is active' : 'Operation paused by administrator'}</b><span>{running ? 'Runtime evaluates missions, agents and business outcomes continuously.' : 'Resume operation when ready.'}</span></div><strong><i className={running ? styles.pulse : ''}/>{running ? 'WORKING' : 'PAUSED'}</strong></div>
  </>
}

function PageHead({ eyebrow, title, text, children }: { eyebrow: string; title: string; text: ReactNode; children?: ReactNode }) { return <div className={styles.pageHead}><div><small className={styles.eyebrow}>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div><div className={styles.headActions}>{children}</div></div> }
function Kpi({ label, value, change, icon }: { label: string; value: string; change: string; icon: ReactNode }) { return <div className={styles.kpi}><header><span>{label}</span>{icon}</header><b>{value}</b><small>{change}</small></div> }
function Head({ title, text, action, onClick }: { title: string; text: string; action: string; onClick: () => void }) { return <header className={styles.panelHead}><div><small>{title}</small><h2>{text}</h2></div><button onClick={onClick}>{action}<ChevronRight size={13}/></button></header> }
function Agent({ n, r, s, v }: { n: string; r: string; s: string; v: string }) { return <div className={styles.agent}><div className={styles.agentIcon}><Bot size={15}/></div><div><b>{n}</b><small>{r}</small></div><span><i className={s === 'Working' ? styles.status : ''}/>{s}</span><strong>{v}</strong></div> }
function ActivityRow({ text, status }: { text: string; status: string }) { return <div className={styles.activity}><i/><div><b>{text}</b><small>Just now</small></div><span>{status}</span></div> }
function Funnel({ metrics }: { metrics: ReturnType<typeof useCompanyRuntime>['metrics'] }) { const items = [['Leads', metrics.leads], ['Qualified', metrics.qualified], ['Opportunities', metrics.opportunities], ['Conversions', metrics.conversions]]; return <div className={styles.funnel}>{items.map(([label, value], i) => <div key={label}><span>{label}</span><strong>{value}</strong><i style={{width:`${Math.max(18, Number(value) / metrics.leads * 100)}%`}}/>{i < 3 && <ChevronRight size={14}/>}</div>)}<footer><b>{metrics.conversionRate}%</b><span>conversion rate</span></footer></div> }
function MetricChart({ history }: { history: Array<{ revenue: number; conversionRate: number }> }) { const max = Math.max(...history.map(x => x.revenue), 1); const points = history.map((x, i) => `${(i / Math.max(1, history.length - 1)) * 700},${225 - (x.revenue / max) * 190}`).join(' '); return <div className={styles.chart}><svg viewBox="0 0 700 250" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="var(--os-blue)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div>{history.map((x, i) => <span key={i}>{x.conversionRate}%</span>)}</div></div> }

function Module({ company, view, open }: { company: Company; view: Exclude<CompanyView, 'Dashboard'>; open: (title:string, body:string)=>void }) {
  if (view === 'Agents') return <AgentsModule company={company} open={open}/>
  if (view === 'Missions') return <MissionsModule company={company} open={open}/>
  if (view === 'Tasks') return <TasksModule open={open}/>
  if (view === 'Marketing') return <MarketingModule/>
  if (view === 'Customers') return <CustomersModule open={open}/>
  if (view === 'Products') return <ProductsModule open={open}/>
  if (view === 'Finance') return <FinanceModule open={open}/>
  if (view === 'Intelligence') return <IntelligenceModule/>
  if (view === 'Knowledge') return <KnowledgeModule open={open}/>
  if (view === 'Operations') return <OperationsModule/>
  if (view === 'Integrations') return <IntegrationsModule open={open}/>
  if (view === 'Security') return <SecurityModule open={open}/>
  if (view === 'Approvals') return <ApprovalsModule/>
  return <SettingsModule open={open}/>
}

function AgentsModule({ company, open }: { company: Company; open: (title:string, body:string)=>void }) { const { counts, metrics } = useCompanyRuntime(); const agents = [['AI Director','Orchestration & strategy','Working','98%'],['Growth Agent','Marketing & acquisition','Working','91%'],['Sales Agent','Pipeline & conversion','Working','87%'],['Analyst Agent','Intelligence & insight','Idle','76%'],['Finance Agent','Financial operations','Working','82%']]; return <><PageHead eyebrow="AI WORKFORCE / AGENTS" title="AI Workforce" text="Digital employees executing the company operating plan."><button className={styles.primary} onClick={() => open('Deploy AI agent','Agent deployment is governed. This simulation prepares the agent configuration; no external deployment or side effect is performed.') }><Bot size={15}/>Deploy agent</button></PageHead><div className={styles.kpis}><Kpi label="Total agents" value={String(company.agents)} change="Registered" icon={<Bot/>}/><Kpi label="Executing" value={String(counts.executing)} change="Live runtime" icon={<Activity/>}/><Kpi label="Completed" value={String(counts.completed)} change="Current run" icon={<CheckCircle2/>}/><Kpi label="Conversion" value={`${metrics.conversionRate}%`} change="Sales outcome" icon={<Target/>}/></div><section className={styles.panel}><Head title="WORKFORCE" text="Agents and current execution" action="Configure" onClick={()=>open('Workforce configuration','Agent workforce configuration is available here. Changes remain inside the company tenant until explicitly authorized.')}/>{agents.map(a=><button type="button" className={styles.row} key={a[0]} onClick={() => open(a[0], `${a[1]} · Status: ${a[2]} · Efficiency: ${a[3]}. Agent controls are tenant-scoped and governed.`)}><div><Bot size={16}/></div><span><b>{a[0]}</b><small>{a[1]}</small></span><strong className={a[2] === 'Working' ? styles.good : ''}><i className={a[2] === 'Working' ? styles.status : ''}/>{a[2].toUpperCase()}</strong><b className={styles.score}>{a[3]}</b><ChevronRight size={15}/></button>)}</section></> }
function MissionsModule({ company, open }: { company: Company; open: (title:string, body:string)=>void }) { const { progress, counts } = useCompanyRuntime(); const missions = [company.objective,'Increase conversion efficiency','Improve customer retention','Automate weekly financial reporting']; return <><PageHead eyebrow="AI WORKFORCE / MISSIONS" title="Missions" text="Strategic objectives decomposed into autonomous execution."><button className={styles.primary} onClick={() => open('Create mission','Mission creation is ready as a governed workspace action. Define the objective, priority, budget and approval policy before activation.') }><Target size={15}/>Create mission</button></PageHead><div className={styles.kpis}><Kpi label="Active missions" value={String(company.missions)} change={`${progress}% execution`} icon={<Target/>}/><Kpi label="Executing" value={String(counts.executing)} change="Tasks now" icon={<Bot/>}/><Kpi label="Completed" value={String(counts.completed)} change="Runtime" icon={<Zap/>}/><Kpi label="Blocked" value={String(counts.blocked)} change="Requires review" icon={<Clock3/>}/></div><section className={styles.panel}>{missions.map((m,i)=><button type="button" className={styles.row} key={m} onClick={() => open('Mission details', `${m}. Mission status, progress, strategy and governance controls are available here.`)}><div><Target size={16}/></div><span><b>{m}</b><small>{i === 0 ? 'Current company priority' : 'Autonomous execution'}</small><div className={styles.progress}><i style={{width:`${Math.min(98,progress+i*7)}%`}}/></div></span><strong>{Math.min(98,progress+i*7)}%</strong><ChevronRight size={15}/></button>)}</section></> }
function TasksModule({ open }: { open: (title:string, body:string)=>void }) { const { runtime, counts } = useCompanyRuntime(); const tasks = runtime.plan.tasks; return <><PageHead eyebrow="AI WORKFORCE / TASKS" title="Tasks" text="Execution queue generated by the operating engine."><span className={styles.live}><i/>LIVE</span></PageHead><div className={styles.kpis}><Kpi label="Completed" value={String(counts.completed)} change="Current run" icon={<CheckCircle2/>}/><Kpi label="Executing" value={String(counts.executing)} change="Now" icon={<Activity/>}/><Kpi label="Blocked" value={String(counts.blocked)} change="Attention" icon={<Clock3/>}/><Kpi label="Total" value={String(tasks.length)} change="Plan size" icon={<Database/>}/></div><section className={styles.panel}>{tasks.map(task=><button type="button" className={styles.row} key={task.id} onClick={() => open(`Task ${task.id}`, `${task.title} · Status: ${task.status}. Task detail and execution evidence are available without triggering an external side effect.`)}><div><Zap size={16}/></div><span><b>{task.title}</b><small>{task.id}</small></span><strong className={task.status === 'COMPLETED' ? styles.good : ''}>{task.status}</strong><ChevronRight size={15}/></div>)}</section></> }
function MarketingModule() { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / MARKETING" title="Marketing" desc="Acquisition, campaigns and conversion intelligence."><div className={styles.kpis}><Kpi label="Leads" value={String(metrics.leads)} change="Live acquisition" icon={<Users/>}/><Kpi label="Qualified" value={String(metrics.qualified)} change="Pipeline ready" icon={<Target/>}/><Kpi label="Opportunities" value={String(metrics.opportunities)} change="Sales pipeline" icon={<Megaphone/>}/><Kpi label="Conversion Rate" value={`${metrics.conversionRate}%`} change={`${metrics.conversionDelta >= 0 ? '+' : ''}${metrics.conversionDelta}% live`} icon={<Activity/>}/></div><section className={styles.module}><section className={styles.panel}><Head title="FUNNEL" text="Acquisition to revenue" action="" onClick={()=>{}}/><Funnel metrics={metrics}/></section><aside className={styles.panel}><small>AI RECOMMENDATION</small><h2>Protect conversion quality</h2><p>The runtime is monitoring opportunities and conversion outcomes before increasing acquisition volume.</p><div className={styles.callout}><Target size={16}/><span>Current conversion <b>{metrics.conversionRate}%</b></span></div></aside></section></MetricModule> }
function CustomersModule({ open }: { open: (title:string, body:string)=>void }) { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / CUSTOMERS" title="Customers" desc="Customer lifecycle, retention and commercial outcomes."><section className={styles.module}><section className={styles.panel}>{['Prospects','Qualified leads','Active customers','Retention signals'].map((x,i)=><button type="button" className={styles.row} key={x} onClick={() => open(x, i === 4 ? 'API endpoint is prepared. Activation remains blocked until authorization, minimization review, sandbox validation and deployment policy checks pass.' : 'Integration is prepared but activation is governed. No external connection is opened from this dashboard.')}><div><Users size={16}/></div><span><b>{x}</b><small>Managed by AI Company OS</small></span><strong>{[metrics.leads,metrics.qualified,metrics.conversions,Math.max(1,metrics.conversions-2)][i]}</strong><ChevronRight size={15}/></button>)}</section><aside className={styles.panel}><small>CUSTOMER ECONOMICS</small><h2>{formatMoney(metrics.ltv)}</h2><p>Estimated LTV</p><hr/><p>CAC <b>{formatMoney(metrics.cac)}</b></p><p>Conversions <b>{metrics.conversions}</b></p></aside></section></MetricModule> }
function ProductsModule({ open }: { open: (title:string, body:string)=>void }) { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / PRODUCTS" title="Products" desc="Portfolio performance and product economics."><section className={styles.module}><section className={styles.panel}>{['Core subscription','AI automation package','Enterprise workflow','Expansion module'].map((x,i)=><button type="button" className={styles.row} key={x} onClick={() => open(x, 'Security control surface opened. Sensitive changes require authenticated authorization and will be recorded in the audit trail.')}><div><Package size={16}/></div><span><b>{x}</b><small>{i<2?'Active product':'Planned / experimental'}</small></span><strong>{i<2?formatMoney(Math.round(metrics.revenue*(0.36-i*0.08))):'READY'}</strong><ChevronRight size={15}/></button>)}</section><aside className={styles.panel}><small>PORTFOLIO SIGNAL</small><h2>{metrics.conversionRate}%</h2><p>Overall commercial conversion</p><div className={styles.progress}><i style={{width:`${Math.min(100,metrics.conversionRate*2.5)}%`}}/></div></aside></section></MetricModule> }
function FinanceModule({ open }: { open: (title:string, body:string)=>void }) { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / FINANCE" title="Finance" desc="Revenue, expenses, profit and recurring economics."><div className={styles.kpis}><Kpi label="Revenue" value={formatMoney(metrics.revenue)} change="Runtime" icon={<CircleDollarSign/>}/><Kpi label="Expenses" value={formatMoney(metrics.expenses)} change="Operating" icon={<Wallet/>}/><Kpi label="Profit" value={formatMoney(metrics.profit)} change={`${metrics.roi}% ROI`} icon={<WalletCards/>}/><Kpi label="MRR" value={formatMoney(metrics.mrr)} change="Modelled recurring" icon={<CircleDollarSign/>}/></div><section className={styles.panel}><Head title="FINANCIAL SIGNAL" text="Current economics" action="Intelligence" onClick={() => open('Financial intelligence', 'Financial intelligence is available as a read-only analysis surface. External financial actions remain blocked by governance.')}/><div className={styles.financial}><b>{metrics.roi}%</b><span>ROI</span><div className={styles.progress}><i style={{width:`${Math.min(100,Math.max(10,metrics.roi))}%`}}/></div><p>Revenue is updated by the controlled runtime simulation; no external financial side effects are performed.</p></div></section></MetricModule> }
function IntelligenceModule() { const { metrics, metricEvent } = useCompanyRuntime(); return <MetricModule eyebrow="INTELLIGENCE" title="Intelligence" desc="Evidence-backed signals generated from company activity."><section className={styles.module}><section className={styles.panel}>{[['Conversion',`${metrics.conversionRate}%`,'Sales efficiency'],['Revenue',formatMoney(metrics.revenue),'Commercial output'],['ROI',`${metrics.roi}%`,'Financial efficiency'],['LTV',formatMoney(metrics.ltv),'Customer economics']].map(([a,b,c])=><div className={styles.insight} key={a}><div><small>{a}</small><b>{b}</b></div><span>{c}</span></div>)}</section><aside className={styles.panel}><small>LATEST SIGNAL</small><h2>{metricEvent}</h2><p>Generated from the controlled runtime event stream.</p><div className={styles.callout}><BrainCircuit size={16}/><span>Confidence <b>92%</b></span></div></aside></section></MetricModule> }
function KnowledgeModule({ open }: { open: (title:string, body:string)=>void }) { return <MetricModule eyebrow="INTELLIGENCE / KNOWLEDGE" title="Knowledge" desc="The company memory layer for decisions, documents and lessons."><section className={styles.module}>{['Company policies','Mission decisions','Customer knowledge','Agent lessons learned'].map((x,i)=><div className={styles.panel} key={x}><Database size={18}/><h2>{x}</h2><p>{[24,18,42,11][i]} knowledge items indexed for future retrieval.</p><button className={styles.secondary} onClick={() => open(x, `${[24,18,42,11][i]} knowledge items are indexed. Memory inspection is read-only in this view.`)}>Open memory</button></div>)}</section></MetricModule> }
function OperationsModule() { const { running, counts } = useCompanyRuntime(); return <MetricModule eyebrow="SYSTEM / OPERATIONS" title="Operations" desc="Execution controls, runtime health and exception handling."><div className={styles.kpis}><Kpi label="Runtime" value={running?'LIVE':'PAUSED'} change="Simulation" icon={<Activity/>}/><Kpi label="Executing" value={String(counts.executing)} change="Now" icon={<Zap/>}/><Kpi label="Blocked" value={String(counts.blocked)} change="Attention" icon={<ShieldCheck/>}/><Kpi label="Side effects" value="0" change="Safety constraint" icon={<CheckCircle2/>}/></div><section className={styles.panel}><div className={styles.callout}><ShieldCheck size={18}/><span>Simulation only · no external side effects · runtime is deterministic and reversible.</span></div></section></MetricModule> }
function IntegrationsModule({ open }: { open: (title:string, body:string)=>void }) { return <MetricModule eyebrow="SYSTEM / INTEGRATIONS" title="Integrations" desc="Connected services and future data sources."><section className={styles.panel}>{['CRM / Customer data','Analytics / Intelligence','Communication channels','Payments / Finance','Webhooks / API'].map((x,i)=><button type="button" className={styles.row} key={x} onClick={() => open(x, 'Configuration panel opened. Changes are scoped to this company and require the appropriate authorization.')}><div><PlugZap size={16}/></div><span><b>{x}</b><small>{i===4?'Endpoint ready':'Connection layer ready'}</small></span><strong>{i===4?'READY':'PREPARED'}</strong><ChevronRight size={15}/></button>)}</section></MetricModule> }
function SecurityModule({ open }: { open: (title:string, body:string)=>void }) { return <MetricModule eyebrow="SYSTEM / SECURITY" title="Security" desc="Identity, permissions, audit and operational safety."><section className={styles.module}><section className={styles.panel}>{['Identity & session','Role permissions','Audit trail','Runtime safety'].map(x=><button type="button" className={styles.row} key={x} onClick={() => open(x, 'Customer lifecycle detail opened. This view is read-only until a governed action is explicitly authorized.')}><div><ShieldCheck size={16}/></div><span><b>{x}</b><small>Control surface operational</small></span><strong className={styles.good}>ACTIVE</strong><CheckCircle2 size={15}/></button>)}</section><aside className={styles.panel}><small>SECURITY STATUS</small><h2>Protected</h2><p>Company session is controlled by role-aware access surfaces.</p></aside></section></MetricModule> }
function SettingsModule({ open }: { open: (title:string, body:string)=>void }) { return <MetricModule eyebrow="SYSTEM / SETTINGS" title="Settings" desc="Company configuration, preferences and operating policies."><section className={styles.panel}>{['Company profile','AI operating policy','Notifications','Experience preferences','Data & privacy'].map(x=><button type="button" className={styles.row} key={x} onClick={() => open(x, 'Product detail opened. Product changes require the appropriate company authorization.')}><div><Settings size={16}/></div><span><b>{x}</b><small>Configuration available</small></span><ChevronRight size={15}/></div>)}</section></MetricModule> }
function MetricModule({ eyebrow, title, desc, children }: { eyebrow: string; title: string; desc: string; children: ReactNode }) { return <><PageHead eyebrow={eyebrow} title={title} text={desc}><span className={styles.live}><i/>LIVE</span></PageHead>{children}</> }

function ActionModal({ title, body, onClose }: { title:string; body:string; onClose:()=>void }) {
  return <div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:1000,display:'grid',placeItems:'center',background:'rgba(0,0,0,.62)',padding:24}}>
    <section style={{maxWidth:560,width:'100%',padding:28,borderRadius:18,background:'var(--os-panel,#0e232b)',border:'1px solid rgba(229,205,154,.22)',boxShadow:'0 24px 80px rgba(0,0,0,.45)'}}>
      <small style={{letterSpacing:'.12em',opacity:.65}}>CONTROL ACTION</small><h2 style={{margin:'8px 0 12px'}}>{title}</h2><p style={{lineHeight:1.6,opacity:.82}}>{body}</p>
      <div style={{display:'flex',justifyContent:'flex-end',marginTop:24}}><button className={styles.primary} onClick={onClose}>Close</button></div>
    </section>
  </div>
}
