'use client'

import type { ReactNode } from 'react'
import { Activity, Bot, BrainCircuit, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, Database, Megaphone, Package, PlugZap, Settings, ShieldCheck, Target, Users, Wallet, WalletCards, Zap } from 'lucide-react'
import styles from '../../app/company/[companyId]/CompanyRuntimeWorkspace.module.css'
import { formatMoney } from '../../lib/business-metrics'
import { useCompanyRuntime } from '../../app/company/[companyId]/CompanyRuntimeContext'
import type { CompanyView } from './CompanyNavigation'
import ApprovalsModule from './CompanyApprovals'

type Company = { name: string; type: string; revenue: string; profit: string; health: string; agents: number; missions: number; objective: string }

type Props = { company: Company; view: CompanyView; setView: (view: CompanyView) => void }

export default function CompanyRuntimeContent({ company, view, setView }: Props) {
  return <>{view === 'Dashboard' ? <Dashboard company={company} setView={setView}/> : <Module company={company} view={view}/>}</>
}

function Dashboard({ company, setView }: { company: Company; setView: (v: CompanyView) => void }) {
  const { running, setRunning, metrics, progress, counts, metricEvent, lastAction } = useCompanyRuntime()
  return <>
    <PageHead eyebrow="COMPANY COMMAND CENTER" title="O que precisa acontecer agora?" text={<>Você define a intenção. O AI Company OS decide quais sistemas, agentes e processos precisam agir.</>}>
      <span className={styles.live}><i/>LIVE</span>
      <button className={styles.primary} onClick={() => setRunning(!running)}><Activity size={15}/>{running ? 'AI running' : 'AI paused'}</button>
    </PageHead>
    <section className={styles.director} style={{marginBottom:18}}>
      <div><small>AI DIRECTOR</small><b>{running ? 'A empresa está sendo conduzida continuamente.' : 'A operação está pausada.'}</b><span>{running ? 'Agentes monitoram eventos, executam tarefas e pedem sua intervenção somente quando necessário.' : 'Retome a operação quando quiser.'}</span></div>
      <strong><i className={running ? styles.pulse : ''}/>{running ? 'WORKING' : 'PAUSED'}</strong>
    </section>
    <section className={styles.panel} style={{marginBottom:18}}>
      <small style={{letterSpacing:'.12em',color:'var(--os-muted)'}}>INTENÇÃO DA EMPRESA</small>
      <h2 style={{margin:'8px 0 6px'}}>Fale com sua empresa</h2>
      <p style={{margin:'0 0 14px',color:'var(--os-muted)'}}>Escreva um objetivo. O sistema transforma a intenção em plano, tarefas, agentes, agenda, comunicação e acompanhamento.</p>
      <div style={{display:'flex',gap:10,alignItems:'center',padding:'13px 15px',border:'1px solid rgba(255,255,255,.08)',borderRadius:12,background:'rgba(255,255,255,.025)'}}>
        <BrainCircuit size={17}/><span style={{flex:1,color:'#b9cbd0'}}>Ex.: “Aumente as vendas este mês sem ultrapassar €300 de marketing.”</span>
        <button className={styles.secondary} onClick={() => setView('Marketing')}>Começar</button>
      </div>
    </section>
    <div className={styles.kpis}>
      <Kpi label="Revenue" value={formatMoney(metrics.revenue)} change="Runtime result" icon={<CircleDollarSign/>}/>
      <Kpi label="Customers" value={String(metrics.conversions)} change="Current conversions" icon={<Users/>}/>
      <Kpi label="AI Workforce" value={String(company.agents)} change={String(counts.executing) + ' executing'} icon={<Bot/>}/>
      <Kpi label="Company Health" value={company.health} change="Operational" icon={<Activity/>}/>
    </div>
    <div className={styles.grid}>
      <section className={styles.panel}><Head title="WHAT IS HAPPENING" text="Live company activity" action="" onClick={()=>{}}/><ActivityRow text={metricEvent} status="LIVE"/><ActivityRow text={lastAction} status="RUNTIME"/><ActivityRow text={String(counts.completed) + ' tasks completed by the runtime'} status="DONE"/></section>
      <section className={styles.panel}><Head title="WHAT NEEDS YOU" text="Human decisions only" action="" onClick={()=>{}}/><div className={styles.callout}><ShieldCheck size={16}/><span>No critical approval is waiting right now.</span></div><p style={{color:'var(--os-muted)',fontSize:12,marginTop:12}}>When an action requires permission, budget approval or a policy decision, it appears here.</p></section>
    </div>
    <div className={styles.grid2}>
      <section className={styles.panel}><Head title="BUSINESS SIGNAL" text="Commercial movement" action="Marketing" onClick={() => setView('Marketing')}/><Funnel metrics={metrics}/></section>
      <section className={styles.panel}><Head title="AI WORKFORCE" text="Autonomous execution" action="Agents" onClick={() => setView('Agents')}/><Agent n="AI Director" r="Orchestration & strategy" s="Working" v="98%"/><Agent n="Growth Agent" r="Marketing & acquisition" s="Working" v="91%"/><Agent n="Sales Agent" r="Pipeline & conversion" s="Working" v="87%"/></section>
    </div>
  </>
}

function PageHead({ eyebrow, title, text, children }: { eyebrow: string; title: string; text: ReactNode; children?: ReactNode }) { return <div className={styles.pageHead}><div><small className={styles.eyebrow}>{eyebrow}</small><h1>{title}</h1><p>{text}</p></div><div className={styles.headActions}>{children}</div></div> }
function Kpi({ label, value, change, icon }: { label: string; value: string; change: string; icon: ReactNode }) { return <div className={styles.kpi}><header><span>{label}</span>{icon}</header><b>{value}</b><small>{change}</small></div> }
function Head({ title, text, action, onClick }: { title: string; text: string; action: string; onClick: () => void }) { return <header className={styles.panelHead}><div><small>{title}</small><h2>{text}</h2></div><button onClick={onClick}>{action}<ChevronRight size={13}/></button></header> }
function Agent({ n, r, s, v }: { n: string; r: string; s: string; v: string }) { return <div className={styles.agent}><div className={styles.agentIcon}><Bot size={15}/></div><div><b>{n}</b><small>{r}</small></div><span><i className={s === 'Working' ? styles.status : ''}/>{s}</span><strong>{v}</strong></div> }
function ActivityRow({ text, status }: { text: string; status: string }) { return <div className={styles.activity}><i/><div><b>{text}</b><small>Just now</small></div><span>{status}</span></div> }
function Funnel({ metrics }: { metrics: ReturnType<typeof useCompanyRuntime>['metrics'] }) { const items = [['Leads', metrics.leads], ['Qualified', metrics.qualified], ['Opportunities', metrics.opportunities], ['Conversions', metrics.conversions]]; return <div className={styles.funnel}>{items.map(([label, value], i) => <div key={label}><span>{label}</span><strong>{value}</strong><i style={{width:`${Math.max(18, Number(value) / metrics.leads * 100)}%`}}/>{i < 3 && <ChevronRight size={14}/>}</div>)}<footer><b>{metrics.conversionRate}%</b><span>conversion rate</span></footer></div> }
function MetricChart({ history }: { history: Array<{ revenue: number; conversionRate: number }> }) { const max = Math.max(...history.map(x => x.revenue), 1); const points = history.map((x, i) => `${(i / Math.max(1, history.length - 1)) * 700},${225 - (x.revenue / max) * 190}`).join(' '); return <div className={styles.chart}><svg viewBox="0 0 700 250" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="var(--os-blue)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"/></svg><div>{history.map((x, i) => <span key={i}>{x.conversionRate}%</span>)}</div></div> }

function Module({ company, view }: { company: Company; view: Exclude<CompanyView, 'Dashboard'> }) {
  if (view === 'Agents') return <AgentsModule company={company}/>
  if (view === 'Missions') return <MissionsModule company={company}/>
  if (view === 'Tasks') return <TasksModule/>
  if (view === 'Marketing') return <MarketingModule/>
  if (view === 'Customers') return <CustomersModule/>
  if (view === 'Products') return <ProductsModule/>
  if (view === 'Finance') return <FinanceModule/>
  if (view === 'Intelligence') return <IntelligenceModule/>
  if (view === 'Knowledge') return <KnowledgeModule/>
  if (view === 'Operations') return <OperationsModule/>
  if (view === 'Integrations') return <IntegrationsModule/>
  if (view === 'Security') return <SecurityModule/>
  if (view === 'Approvals') return <ApprovalsModule/>
  return <SettingsModule/>
}

function AgentsModule({ company }: { company: Company }) { const { counts, metrics } = useCompanyRuntime(); const agents = [['AI Director','Orchestration & strategy','Working','98%'],['Growth Agent','Marketing & acquisition','Working','91%'],['Sales Agent','Pipeline & conversion','Working','87%'],['Analyst Agent','Intelligence & insight','Idle','76%'],['Finance Agent','Financial operations','Working','82%']]; return <><PageHead eyebrow="AI WORKFORCE / AGENTS" title="AI Workforce" text="Digital employees executing the company operating plan."><button className={styles.primary}><Bot size={15}/>Deploy agent</button></PageHead><div className={styles.kpis}><Kpi label="Total agents" value={String(company.agents)} change="Registered" icon={<Bot/>}/><Kpi label="Executing" value={String(counts.executing)} change="Live runtime" icon={<Activity/>}/><Kpi label="Completed" value={String(counts.completed)} change="Current run" icon={<CheckCircle2/>}/><Kpi label="Conversion" value={`${metrics.conversionRate}%`} change="Sales outcome" icon={<Target/>}/></div><section className={styles.panel}><Head title="WORKFORCE" text="Agents and current execution" action="" onClick={()=>{}}/>{agents.map(a=><div className={styles.row} key={a[0]}><div><Bot size={16}/></div><span><b>{a[0]}</b><small>{a[1]}</small></span><strong className={a[2] === 'Working' ? styles.good : ''}><i className={a[2] === 'Working' ? styles.status : ''}/>{a[2].toUpperCase()}</strong><b className={styles.score}>{a[3]}</b><ChevronRight size={15}/></div>)}</section></> }
function MissionsModule({ company }: { company: Company }) { const { progress, counts } = useCompanyRuntime(); const missions = [company.objective,'Increase conversion efficiency','Improve customer retention','Automate weekly financial reporting']; return <><PageHead eyebrow="AI WORKFORCE / MISSIONS" title="Missions" text="Strategic objectives decomposed into autonomous execution."><button className={styles.primary}><Target size={15}/>Create mission</button></PageHead><div className={styles.kpis}><Kpi label="Active missions" value={String(company.missions)} change={`${progress}% execution`} icon={<Target/>}/><Kpi label="Executing" value={String(counts.executing)} change="Tasks now" icon={<Bot/>}/><Kpi label="Completed" value={String(counts.completed)} change="Runtime" icon={<Zap/>}/><Kpi label="Blocked" value={String(counts.blocked)} change="Requires review" icon={<Clock3/>}/></div><section className={styles.panel}>{missions.map((m,i)=><div className={styles.row} key={m}><div><Target size={16}/></div><span><b>{m}</b><small>{i === 0 ? 'Current company priority' : 'Autonomous execution'}</small><div className={styles.progress}><i style={{width:`${Math.min(98,progress+i*7)}%`}}/></div></span><strong>{Math.min(98,progress+i*7)}%</strong><ChevronRight size={15}/></div>)}</section></> }
function TasksModule() { const { runtime, counts } = useCompanyRuntime(); const tasks = runtime.plan.tasks; return <><PageHead eyebrow="AI WORKFORCE / TASKS" title="Tasks" text="Execution queue generated by the operating engine."><span className={styles.live}><i/>LIVE</span></PageHead><div className={styles.kpis}><Kpi label="Completed" value={String(counts.completed)} change="Current run" icon={<CheckCircle2/>}/><Kpi label="Executing" value={String(counts.executing)} change="Now" icon={<Activity/>}/><Kpi label="Blocked" value={String(counts.blocked)} change="Attention" icon={<Clock3/>}/><Kpi label="Total" value={String(tasks.length)} change="Plan size" icon={<Database/>}/></div><section className={styles.panel}>{tasks.map(task=><div className={styles.row} key={task.id}><div><Zap size={16}/></div><span><b>{task.title}</b><small>{task.id}</small></span><strong className={task.status === 'COMPLETED' ? styles.good : ''}>{task.status}</strong><ChevronRight size={15}/></div>)}</section></> }
function MarketingModule() { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / MARKETING" title="Marketing" desc="Acquisition, campaigns and conversion intelligence."><div className={styles.kpis}><Kpi label="Leads" value={String(metrics.leads)} change="Live acquisition" icon={<Users/>}/><Kpi label="Qualified" value={String(metrics.qualified)} change="Pipeline ready" icon={<Target/>}/><Kpi label="Opportunities" value={String(metrics.opportunities)} change="Sales pipeline" icon={<Megaphone/>}/><Kpi label="Conversion Rate" value={`${metrics.conversionRate}%`} change={`${metrics.conversionDelta >= 0 ? '+' : ''}${metrics.conversionDelta}% live`} icon={<Activity/>}/></div><section className={styles.module}><section className={styles.panel}><Head title="FUNNEL" text="Acquisition to revenue" action="" onClick={()=>{}}/><Funnel metrics={metrics}/></section><aside className={styles.panel}><small>AI RECOMMENDATION</small><h2>Protect conversion quality</h2><p>The runtime is monitoring opportunities and conversion outcomes before increasing acquisition volume.</p><div className={styles.callout}><Target size={16}/><span>Current conversion <b>{metrics.conversionRate}%</b></span></div></aside></section></MetricModule> }
function CustomersModule() { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / CUSTOMERS" title="Customers" desc="Customer lifecycle, retention and commercial outcomes."><section className={styles.module}><section className={styles.panel}>{['Prospects','Qualified leads','Active customers','Retention signals'].map((x,i)=><div className={styles.row} key={x}><div><Users size={16}/></div><span><b>{x}</b><small>Managed by AI Company OS</small></span><strong>{[metrics.leads,metrics.qualified,metrics.conversions,Math.max(1,metrics.conversions-2)][i]}</strong><ChevronRight size={15}/></div>)}</section><aside className={styles.panel}><small>CUSTOMER ECONOMICS</small><h2>{formatMoney(metrics.ltv)}</h2><p>Estimated LTV</p><hr/><p>CAC <b>{formatMoney(metrics.cac)}</b></p><p>Conversions <b>{metrics.conversions}</b></p></aside></section></MetricModule> }
function ProductsModule() { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / PRODUCTS" title="Products" desc="Portfolio performance and product economics."><section className={styles.module}><section className={styles.panel}>{['Core subscription','AI automation package','Enterprise workflow','Expansion module'].map((x,i)=><div className={styles.row} key={x}><div><Package size={16}/></div><span><b>{x}</b><small>{i<2?'Active product':'Planned / experimental'}</small></span><strong>{i<2?formatMoney(Math.round(metrics.revenue*(0.36-i*0.08))):'READY'}</strong><ChevronRight size={15}/></div>)}</section><aside className={styles.panel}><small>PORTFOLIO SIGNAL</small><h2>{metrics.conversionRate}%</h2><p>Overall commercial conversion</p><div className={styles.progress}><i style={{width:`${Math.min(100,metrics.conversionRate*2.5)}%`}}/></div></aside></section></MetricModule> }
function FinanceModule() { const { metrics } = useCompanyRuntime(); return <MetricModule eyebrow="BUSINESS / FINANCE" title="Finance" desc="Revenue, expenses, profit and recurring economics."><div className={styles.kpis}><Kpi label="Revenue" value={formatMoney(metrics.revenue)} change="Runtime" icon={<CircleDollarSign/>}/><Kpi label="Expenses" value={formatMoney(metrics.expenses)} change="Operating" icon={<Wallet/>}/><Kpi label="Profit" value={formatMoney(metrics.profit)} change={`${metrics.roi}% ROI`} icon={<WalletCards/>}/><Kpi label="MRR" value={formatMoney(metrics.mrr)} change="Modelled recurring" icon={<CircleDollarSign/>}/></div><section className={styles.panel}><Head title="FINANCIAL SIGNAL" text="Current economics" action="Intelligence" onClick={()=>{}}/><div className={styles.financial}><b>{metrics.roi}%</b><span>ROI</span><div className={styles.progress}><i style={{width:`${Math.min(100,Math.max(10,metrics.roi))}%`}}/></div><p>Revenue is updated by the controlled runtime simulation; no external financial side effects are performed.</p></div></section></MetricModule> }
function IntelligenceModule() { const { metrics, metricEvent } = useCompanyRuntime(); return <MetricModule eyebrow="INTELLIGENCE" title="Intelligence" desc="Evidence-backed signals generated from company activity."><section className={styles.module}><section className={styles.panel}>{[['Conversion',`${metrics.conversionRate}%`,'Sales efficiency'],['Revenue',formatMoney(metrics.revenue),'Commercial output'],['ROI',`${metrics.roi}%`,'Financial efficiency'],['LTV',formatMoney(metrics.ltv),'Customer economics']].map(([a,b,c])=><div className={styles.insight} key={a}><div><small>{a}</small><b>{b}</b></div><span>{c}</span></div>)}</section><aside className={styles.panel}><small>LATEST SIGNAL</small><h2>{metricEvent}</h2><p>Generated from the controlled runtime event stream.</p><div className={styles.callout}><BrainCircuit size={16}/><span>Confidence <b>92%</b></span></div></aside></section></MetricModule> }
function KnowledgeModule() { return <MetricModule eyebrow="INTELLIGENCE / KNOWLEDGE" title="Knowledge" desc="The company memory layer for decisions, documents and lessons."><section className={styles.module}>{['Company policies','Mission decisions','Customer knowledge','Agent lessons learned'].map((x,i)=><div className={styles.panel} key={x}><Database size={18}/><h2>{x}</h2><p>{[24,18,42,11][i]} knowledge items indexed for future retrieval.</p><button className={styles.secondary}>Open memory</button></div>)}</section></MetricModule> }
function OperationsModule() { const { running, counts } = useCompanyRuntime(); return <MetricModule eyebrow="SYSTEM / OPERATIONS" title="Operations" desc="Execution controls, runtime health and exception handling."><div className={styles.kpis}><Kpi label="Runtime" value={running?'LIVE':'PAUSED'} change="Simulation" icon={<Activity/>}/><Kpi label="Executing" value={String(counts.executing)} change="Now" icon={<Zap/>}/><Kpi label="Blocked" value={String(counts.blocked)} change="Attention" icon={<ShieldCheck/>}/><Kpi label="Side effects" value="0" change="Safety constraint" icon={<CheckCircle2/>}/></div><section className={styles.panel}><div className={styles.callout}><ShieldCheck size={18}/><span>Simulation only · no external side effects · runtime is deterministic and reversible.</span></div></section></MetricModule> }
function IntegrationsModule() { return <MetricModule eyebrow="SYSTEM / INTEGRATIONS" title="Integrations" desc="Connected services and future data sources."><section className={styles.panel}>{['CRM / Customer data','Analytics / Intelligence','Communication channels','Payments / Finance','Webhooks / API'].map((x,i)=><div className={styles.row} key={x}><div><PlugZap size={16}/></div><span><b>{x}</b><small>{i===4?'Endpoint ready':'Connection layer ready'}</small></span><strong>{i===4?'READY':'PREPARED'}</strong><ChevronRight size={15}/></div>)}</section></MetricModule> }
function SecurityModule() { return <MetricModule eyebrow="SYSTEM / SECURITY" title="Security" desc="Identity, permissions, audit and operational safety."><section className={styles.module}><section className={styles.panel}>{['Identity & session','Role permissions','Audit trail','Runtime safety'].map(x=><div className={styles.row} key={x}><div><ShieldCheck size={16}/></div><span><b>{x}</b><small>Control surface operational</small></span><strong className={styles.good}>ACTIVE</strong><CheckCircle2 size={15}/></div>)}</section><aside className={styles.panel}><small>SECURITY STATUS</small><h2>Protected</h2><p>Company session is controlled by role-aware access surfaces.</p></aside></section></MetricModule> }
function SettingsModule() { return <MetricModule eyebrow="SYSTEM / SETTINGS" title="Settings" desc="Company configuration, preferences and operating policies."><section className={styles.panel}>{['Company profile','AI operating policy','Notifications','Experience preferences','Data & privacy'].map(x=><div className={styles.row} key={x}><div><Settings size={16}/></div><span><b>{x}</b><small>Configuration available</small></span><ChevronRight size={15}/></div>)}</section></MetricModule> }
function MetricModule({ eyebrow, title, desc, children }: { eyebrow: string; title: string; desc: string; children: ReactNode }) { return <><PageHead eyebrow={eyebrow} title={title} text={desc}><span className={styles.live}><i/>LIVE</span></PageHead>{children}</> }
