'use client';
import { useEffect, useState } from 'react';
import { Bot, BrainCircuit, ChartNoAxesCombined, CircleDollarSign, Gauge, LayoutDashboard, Network, Plus, Settings, ShieldCheck, Target, Users, X, Zap } from 'lucide-react';
import Link from 'next/link';

type Company={name:string;type:string;revenue:string;profit:string;health:string;agents:number;missions:number;objective:string};
const nav=[[LayoutDashboard,'Command Center'],[Bot,'Agents'],[Target,'Missions'],[Zap,'Tasks'],[Gauge,'Products'],[Users,'Customers'],[CircleDollarSign,'Finance'],[ChartNoAxesCombined,'Intelligence'],[BrainCircuit,'Knowledge'],[Network,'Operations'],[ShieldCheck,'Security'],[Settings,'Settings']] as const;
const agents=[['CEO Agent','Strategy & Capital','Deciding next allocation','98%'],['Research Agent','Market Intelligence','Validating customer segments','93%'],['Product Agent','Build & Experiments','Building MVP release','96%'],['Sales Agent','Revenue','Preparing growth experiment','91%'],['CFO Agent','Finance & Risk','Monitoring cash and margins','97%']];
const tasks=['Validate pricing experiment #41','Prepare landing page release','Analyze high-intent customer segments','Review weekly cash allocation','Run retention experiment'];
export default function CompanyWorkspace({company,companyId,initialView}:{company:Company;companyId:string;initialView:string}){
 const [view,setView]=useState(initialView||'Command Center'); const [modal,setModal]=useState(''); const [toast,setToast]=useState(''); const [realMoney,setRealMoney]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem('aicos-real-money');setRealMoney(saved==='true')},[]);
 function select(v:string){setView(v);history.replaceState(null,'',`?view=${encodeURIComponent(v.toLowerCase().replaceAll(' ','-'))}`)}
 function action(text:string){setToast(text);setTimeout(()=>setToast(''),2200)}
 return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href="/portfolio">← <span>Portfolio</span></Link><div className="companyIdentity"><span>COMPANY</span><strong>{company.name}</strong><small>{company.type}</small><i><em/> Operational</i></div><nav>{nav.map(([Icon,label])=><button key={label} className={view===label?'active':''} onClick={()=>select(label)}><Icon size={16}/><span>{label}</span></button>)}</nav><div className="companySafety"><ShieldCheck size={15}/><span>Simulation mode<br/><b>Real money {realMoney?'ON':'OFF'}</b></span></div></aside>
 <section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">{company.name} / {view.toUpperCase()}</span><h1>{view}</h1><p>Autonomous operations, measurable growth and controlled execution.</p></div><div className="topStatus"><span><em/> LIVE</span><button onClick={()=>select('Settings')}><Settings size={15}/></button></div></header>
 {view==='Command Center'&&<Command company={company} onAction={action} onView={select}/>} {view==='Agents'&&<Agents onAction={action}/>} {view==='Missions'&&<Missions company={company} onAction={action}/>} {view==='Tasks'&&<Tasks onAction={action}/>} {view==='Products'&&<Products onAction={action}/>} {view==='Customers'&&<Customers/>} {view==='Finance'&&<Finance company={company}/>} {view==='Intelligence'&&<Intelligence/>} {view==='Knowledge'&&<Knowledge/>} {view==='Operations'&&<Operations/>} {view==='Security'&&<Security/>} {view==='Settings'&&<SettingsPanel realMoney={realMoney} setRealMoney={setRealMoney} onAction={action}/>}<footer>AI Company OS · GOAL → MISSION → TASKS → AGENTS → TOOLS → RESULTS → LEARNING → NEXT PLAN</footer></section>
 {modal&&<div className="modalBackdrop" onClick={()=>setModal('')}><div className="createModal" onClick={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setModal('')}><X size={17}/></button><div className="eyebrow">AI COMPANY OS</div><h2>{modal}</h2><p>Simulation action only. No real-world operation is executed.</p><input placeholder="Define the objective or name"/><button className="launchCompany" onClick={()=>{setModal('');action(`${modal} created in simulation`)}}>Create simulation <Plus size={15}/></button></div></div>}
 {toast&&<div className="toast">{toast}</div>}</main>
}
function Command({company,onAction,onView}:{company:Company;onAction:(s:string)=>void;onView:(s:string)=>void}){return <><div className="companyStats"><Stat label="Revenue" value={company.revenue} detail="+18.6% this cycle"/><Stat label="Net profit" value={company.profit} detail="+12.4% this cycle"/><Stat label="AI workforce" value={String(company.agents)} detail="Agents operating"/><Stat label="Company health" value={company.health} detail="Stable · low risk"/></div><section className="missionHero"><div><span className="companyEyebrow">CEO OBJECTIVE · ACTIVE MISSION</span><h2>{company.objective}</h2><p>CEO → Research → Product → Sales → CFO</p><div className="missionProgress"><i style={{width:'71%'}}/></div><small>71% complete · 6 active dependencies</small></div><div className="missionOrb"><b>71%</b><span>MISSION</span></div></section><div className="companyGrid"><section className="panel"><PanelHead title="AI Workforce" action="View all agents" onClick={()=>onView('Agents')}/><div className="agentRows">{agents.slice(0,4).map(a=><Agent key={a[0]} data={a}/>)}</div></section><section className="panel"><PanelHead title="Execution Pipeline" action="Open tasks" onClick={()=>onView('Tasks')}/><div className="pipeline"><Pipe label="Backlog" value="18"/><Pipe label="Planning" value="7"/><Pipe label="Executing" value="9" active/><Pipe label="Completed" value="43"/></div></section><section className="panel wide"><PanelHead title="Live Company Activity" action="Create mission" onClick={()=>onAction('Mission created in simulation')}/><div className="activity">{['Product Agent created pricing experiment #41','Research Agent validated 3 high-intent segments','CEO Agent approved MVP scope and €320 budget','QA Agent opened release validation task'].map((x,i)=><Activity key={x} text={x} time={['12s','48s','2m','4m'][i]}/>)}</div></section></div></>}
function Agents({onAction}:{onAction:(s:string)=>void}){return <section className="module"><ModuleHead title="AI Workforce" subtitle="Roles, status, performance and current decisions" action="Deploy agent" onClick={()=>onAction('Agent deployment queued')}/><div className="cardsGrid">{agents.map(a=><article className="dataCard" key={a[0]}><div className="cardIcon"><Bot size={18}/></div><h3>{a[0]}</h3><span>{a[1]}</span><p>{a[2]}</p><b className="score">{a[3]} efficiency</b><button onClick={()=>onAction(`${a[0]} details opened`)}>Inspect agent →</button></article>)}</div></section>}
function Missions({company,onAction}:{company:Company;onAction:(s:string)=>void}){return <section className="module"><ModuleHead title="Missions" subtitle="Strategic objectives broken into measurable execution" action="New mission" onClick={()=>onAction('Mission created in simulation')}/><div className="tableCard"><Row a="Launch next recurring-revenue product" b="71%" c="Executing"/><Row a={company.objective} b="54%" c="Planning"/><Row a="Improve customer retention" b="32%" c="Research"/><Row a="Reduce operating cost" b="18%" c="Backlog"/></div></section>}
function Tasks({onAction}:{onAction:(s:string)=>void}){return <section className="module"><ModuleHead title="Tasks" subtitle="Execution queue across the AI workforce" action="Create task" onClick={()=>onAction('Task created in simulation')}/><div className="taskList">{tasks.map((t,i)=><div className="taskItem" key={t}><span className={i<2?'taskLive':''}/><div><b>{t}</b><small>{['Product Agent','Research Agent','Sales Agent','CFO Agent','Retention Agent'][i]} · due today</small></div><strong>{['EXECUTING','EXECUTING','PLANNING','REVIEW','BACKLOG'][i]}</strong></div>)}</div></section>}
function Products({onAction}:{onAction:(s:string)=>void}){return <section className="module"><ModuleHead title="Products" subtitle="Offers, experiments and recurring revenue engines" action="New product" onClick={()=>onAction('Product shell created')}/><div className="cardsGrid three"><article className="dataCard"><span>LIVE</span><h3>AI Growth Suite</h3><p>€9,840 MRR · 142 customers</p><b className="score">+22.4% growth</b></article><article className="dataCard"><span>EXPERIMENT</span><h3>Revenue Copilot</h3><p>€2,180 MRR · 31 customers</p><b className="score">+€1.7k expected</b></article><article className="dataCard"><span>BUILDING</span><h3>Retention Engine</h3><p>Targeting 18% churn reduction</p><b className="score">64% validation</b></article></div></section>}
function Customers(){return <section className="module"><ModuleHead title="Customers" subtitle="Customer health, value and growth signals"/><div className="cardsGrid three"><MetricCard title="Active customers" value="412" detail="+14 this cycle"/><MetricCard title="Average LTV" value="€1,840" detail="+8.2%"/><MetricCard title="Retention" value="91.6%" detail="Stable"/></div></section>}
function Finance({company}:{company:Company}){return <section className="module"><ModuleHead title="Finance" subtitle="Capital, revenue, costs and simulated allocation"/><div className="cardsGrid three"><MetricCard title="Revenue" value={company.revenue} detail="+18.6%"/><MetricCard title="Profit" value={company.profit} detail="+12.4%"/><MetricCard title="Cash reserve" value="€28,640" detail="8.4 months runway"/></div><div className="tableCard"><Row a="Marketing experiment" b="-€320" c="Approved"/><Row a="Cloud infrastructure" b="-€1,480" c="Optimized"/><Row a="Expected next revenue" b="+€4,820" c="Forecast"/></div></section>}
function Intelligence(){return <section className="module"><ModuleHead title="Intelligence" subtitle="Signals, opportunities and strategic recommendations"/><div className="signal"><BrainCircuit/><div><b>High-confidence opportunity</b><p>Customers with 3+ active seats show 2.4× higher expansion probability.</p></div><strong>92%</strong></div><div className="signal"><ChartNoAxesCombined/><div><b>Growth signal</b><p>Demand for the current offer is accelerating in two customer segments.</p></div><strong>86%</strong></div></section>}
function Knowledge(){return <section className="module"><ModuleHead title="Knowledge" subtitle="Company memory, documents and learned patterns"/><div className="cardsGrid three"><MetricCard title="Knowledge items" value="1,284" detail="+46 this week"/><MetricCard title="RAG coverage" value="94%" detail="Healthy"/><MetricCard title="Learned patterns" value="87" detail="Validated"/></div></section>}
function Operations(){return <section className="module"><ModuleHead title="Operations" subtitle="Systems, automations and execution health"/><div className="tableCard"><Row a="Agent orchestration" b="99.8%" c="Healthy"/><Row a="Task queue" b="9 active" c="Executing"/><Row a="Integrations" b="12 / 12" c="Connected"/><Row a="Automation runtime" b="98.7%" c="Healthy"/></div></section>}
function Security(){return <section className="module"><ModuleHead title="Security" subtitle="Permissions, risk controls and execution boundaries"/><div className="cardsGrid three"><MetricCard title="Risk level" value="LOW" detail="No critical alerts"/><MetricCard title="Protected actions" value="100%" detail="Permission gated"/><MetricCard title="Real-money actions" value="OFF" detail="Simulation mode"/></div></section>}
function SettingsPanel({realMoney,setRealMoney,onAction}:{realMoney:boolean;setRealMoney:(v:boolean)=>void;onAction:(s:string)=>void}){return <section className="module"><ModuleHead title="Settings" subtitle="Company controls and operating boundaries"/><div className="settingsCard"><label><div><b>Simulation mode</b><small>Keep all company actions inside the safe simulation environment.</small></div><input type="checkbox" checked={!realMoney} onChange={e=>{const v=!e.target.checked;setRealMoney(v);localStorage.setItem('aicos-real-money',String(v));onAction(v?'Real money mode enabled':'Simulation mode enabled')}}/></label><label><div><b>Autonomous planning</b><small>Allow agents to generate the next mission from results.</small></div><input type="checkbox" defaultChecked/></label><label><div><b>Human approval gate</b><small>Require approval before external or financial actions.</small></div><input type="checkbox" defaultChecked/></label></div></section>}
function Stat({label,value,detail}:{label:string;value:string;detail:string}){return <div className="companyStat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function PanelHead({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="panelHead"><div><b>{title}</b><span>Autonomous company operations</span></div><button onClick={onClick}>{action} →</button></div>}
function ModuleHead({title,subtitle,action,onClick}:{title:string;subtitle:string;action?:string;onClick?:()=>void}){return <div className="moduleHead"><div><span className="companyEyebrow">COMPANY MODULE</span><h2>{title}</h2><p>{subtitle}</p></div>{action&&<button onClick={onClick}>{action} <Plus size={14}/></button>}</div>}
function Agent({data}:{data:string[]}){return <div className="agentRow"><div className="agentIcon"><Bot size={16}/></div><div><b>{data[0]}</b><small>{data[1]}</small><span>{data[2]}</span></div><strong>{data[3]}</strong></div>}
function Pipe({label,value,active}:{label:string;value:string;active?:boolean}){return <div className={active?'pipe activePipe':'pipe'}><span>{label}</span><b>{value}</b><i><em style={{width:`${Math.min(Number(value)*2,100)}%`}}/></i></div>}
function Activity({text,time}:{text:string;time:string}){return <div className="activityRow"><i/><div><b>{text}</b><small>{time}</small></div></div>}
function Row({a,b,c}:{a:string;b:string;c:string}){return <div className="tableRow"><b>{a}</b><strong>{b}</strong><span>{c}</span></div>}
function MetricCard({title,value,detail}:{title:string;value:string;detail:string}){return <article className="metricCard"><small>{title}</small><b>{value}</b><span>{detail}</span></article>}
