'use client';
import {useState} from 'react';
import {Activity,Bot,BrainCircuit,BriefcaseBusiness,CircleDollarSign,Gauge,LayoutDashboard,LineChart,Network,Settings,ShieldCheck,Target,Users,WalletCards,Zap,ArrowUpRight} from 'lucide-react';
const nav=[[LayoutDashboard,'Overview'],[BriefcaseBusiness,'Company'],[Bot,'Agents'],[Target,'Tasks'],[LineChart,'Projects'],[WalletCards,'Finance'],[BrainCircuit,'Strategy'],[Network,'Memory'],[Settings,'Settings']] as const;
const rooms=[['sales','Sales','Revenue Engine',['AL','PR','SD']],['product','Product','Build & Research',['DV','QA','RS']],['ops','Operations','Execution',['OP','AU']],['finance','Finance','Capital & Risk',['CF','AN']]] as const;
const people=[['CE','CEO Agent','Executive','Deciding capital allocation','98%'],['CF','CFO Agent','Finance','Monitoring portfolio risk','96%'],['AL','Sales Agent','Sales','Following qualified leads','91%'],['DV','Product Agent','Product','Building pricing experiment','94%'],['RS','Research Agent','Research','Scanning opportunities','89%'],['OP','Operations Agent','Operations','Executing workflows','93%'],['QA','QA Agent','Product','Validating release','97%'],['AN','Quant Agent','Finance','Backtesting strategies','92%']] as const;
const tasks=[['T-104','Analyze SaaS opportunities','Research','Executing','RS'],['T-105','Backtest momentum strategy','Finance','Executing','AN'],['T-106','Launch pricing experiment','Product','Planning','DV'],['T-107','Contact qualified leads','Sales','Executing','AL'],['T-108','Update risk model','Finance','Backlog','CF'],['T-109','Automate onboarding','Operations','Completed','OP']] as const;
type PersonId=(typeof people)[number][0];
export default function Home(){const[v,setV]=useState('Overview');const[a,setA]=useState<PersonId|null>(null);return <main className="os"><aside className="sidebar"><div className="brand"><div className="brandMark">AI</div><div><div className="brandName">AI Company OS</div><div className="brandSub">AUTONOMOUS COMPANY</div></div></div><nav className="nav">{nav.map(([I,n])=><button key={n} className={v===n?'active':''} onClick={()=>setV(n)}><I size={16}/><span>{n}</span></button>)}</nav><div className="sideBottom"><div className="status"><i className="dot"/>System operational</div></div></aside><section className="main"><header className="topbar"><div><div className="eyebrow">Company command center</div><div className="title">{v==='Overview'?'Good evening, CEO':v}</div></div><div className="actions"><div className="pill">Simulation · Day 37</div><button className="iconBtn" onClick={()=>setV('Settings')}><Settings size={15}/></button></div></header>{v==='Overview'&&<Overview open={setA}/>} {v==='Company'&&<Company open={setA}/>} {v==='Agents'&&<Agents open={setA}/>} {v==='Tasks'&&<Tasks/>} {v==='Projects'&&<Projects/>} {v==='Finance'&&<Finance/>} {v==='Strategy'&&<Strategy/>} {v==='Memory'&&<Memory/>} {v==='Settings'&&<SettingsView/>}<div className="footerNote">AI Company OS · Goal → Plan → Agents → Tools → Results → Learning → New Plan</div></section>{a&&<Drawer id={a} close={()=>setA(null)}/>}</main>}
function Overview({open}:{open:(x:PersonId)=>void}){return <><div className="gridStats"><Stat l="Cash balance" v="€18,420" t="+€2,840 this month"/><Stat l="Revenue" v="€42,860" t="+18.7% vs last month"/><Stat l="Active agents" v="14 / 16" t="12 working · 2 waiting"/><Stat l="Open tasks" v="37" t="9 completed today"/><Stat l="Company health" v="94%" t="↑ 6% this week"/></div><div className="decision card"><div><div className="eyebrow">CEO decision center</div><div className="decisionTitle">Grow capital while protecting downside</div><div className="sectionMeta">Current objective · Increase company net worth by 25% this cycle</div></div><button onClick={()=>open('CE')}>Open CEO</button></div><div className="dashboard"><div className="card floor"><Head title="Company Floor" meta="Every room is an autonomous department"/><Floor open={open}/></div><div className="card live"><Head title="Live Activity" meta="What the company is doing now"/><div className="activity">{[['Sales Agent','qualified a new enterprise lead worth €18,400','12s'],['CEO Agent','approved the growth experiment','48s'],['Research Agent','found a pricing opportunity','2m'],['CFO Agent','updated runway forecast','4m'],['Automation Agent','completed onboarding workflow','7m'],['QA Agent','validated release candidate','11m']].map(x=><div className="activityItem" key={x[0]}><div className="activityIcon"><Activity size={14}/></div><div className="activityText"><strong>{x[0]}</strong> {x[1]}</div><div className="time">{x[2]}</div></div>)}</div></div></div><div className="bottom"><div className="card pipeline"><Head title="Execution Pipeline" meta="Work moving through the company"/><div className="pipelineRows"><Stage n="Backlog" c="18"/><Stage n="Planning" c="7"/><Stage n="Executing" c="9"/><Stage n="Completed" c="43"/></div></div><div className="card loop"><Head title="Autonomous Loop" meta="The company learns and repeats"/><div className="loopLine">{['Goal','Plan','Execute','Evaluate','Learn'].map((x,i)=><span key={x}>{i?'→ ':''}<b>{x}</b></span>)}</div></div></div></>}
function Floor({open}:{open:(x:PersonId)=>void}){return <div className="companyFloor"><div className="room ceo"><div className="roomName">Executive</div><div className="roomLead">CEO · Strategy</div><div className="agents"><Agent x="CE" open={()=>open('CE')}/><Agent x="ST"/></div></div>{rooms.map(r=><div className={`room ${r[0]}`} key={r[1]}><div className="roomName">{r[1]}</div><div className="roomLead">{r[2]}</div><div className="agents">{r[3].map((x,i)=><Agent key={x} x={x} work={i===0} open={x==='CF'?'CF':x==='AN'?'AN':x==='AL'?'AL':x==='DV'?'DV':x==='RS'?'RS':x==='OP'?'OP':x==='QA'?'QA':undefined}/>)}</div></div>)}</div>}
function Agents({open}:{open:(x:PersonId)=>void}){return <><Panel t="AI Workforce" m="Agents are employees: role, objective, memory, tools and performance"/><div className="agentGrid">{people.map(p=><button className="agentCard" key={p[0]} onClick={()=>open(p[0])}><div className="agentAvatar">{p[0]}</div><div className="agentInfo"><strong>{p[1]}</strong><span>{p[2]}</span><p>{p[3]}</p><div className="bar"><i style={{width:p[4]}}/></div></div><b>{p[4]}</b></button>)}</div></>}
function Tasks(){return <><Panel t="Task Command" m="Every objective becomes executable work"/><div className="taskBoard">{['Backlog','Planning','Executing','Completed'].map(s=><div className="taskCol" key={s}><div className="colHead"><span>{s}</span><b>{tasks.filter(x=>x[3]===s).length}</b></div>{tasks.filter(x=>x[3]===s).map(x=><div className="taskCard" key={x[0]}><small>{x[0]} · {x[2]}</small><strong>{x[1]}</strong><span>Agent {x[4]}</span></div>)}</div>)}</div></>}
function Company({open}:{open:(x:PersonId)=>void}){return <><Panel t="Company World" m="A living organization with autonomous departments"/><div className="companyWide card"><Floor open={open}/></div><div className="threeCols"><Metric title="Capital Engine" v="€18,420" d="€2,840 generated"/><Metric title="Growth" v="+18.7%" d="Revenue versus last cycle"/><Metric title="Risk" v="Low" d="No critical exposure"/></div></>}
function Projects(){return <><Panel t="Business Projects" m="The company invests resources into projects that can create value"/><div className="projectGrid">{[['AI Support SaaS','Building','€3,200','€7,840'],['Trading Research Lab','Backtesting','€2,000','€0'],['Enterprise Automation','Selling','€1,400','€18,400']].map(p=><div className="card projectCard" key={p[0]}><div className="projectTop"><span>{p[1]}</span><ArrowUpRight size={15}/></div><h2>{p[0]}</h2><div className="projectStats"><span>Capital<strong>{p[2]}</strong></span><span>Revenue<strong>{p[3]}</strong></span></div><div className="bar"><i style={{width:p[1]==='Selling'?'78%':p[1]==='Building'?'46%':'31%'}}/></div></div>)}</div></>}
function Finance(){return <><Panel t="Capital & Markets" m="Simulated financial operations — no real orders are executed"/><div className="financeHero card"><div><div className="eyebrow">Portfolio</div><div className="bigMoney">€18,420</div><div className="positive">+€2,840 · +18.2%</div></div><div className="allocation">{[['Cash Reserve','35%'],['Business Operations','32%'],['Market Strategies','18%'],['Growth Experiments','15%']].map(x=><div className="alloc" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div><div className="threeCols"><Metric title="Market Lab" v="12 strategies" d="4 profitable in backtest"/><Metric title="Risk Budget" v="€2,000" d="Maximum simulated exposure"/><Metric title="Runway" v="147 days" d="Based on current burn"/></div></>}
function Strategy(){return <><Panel t="CEO Strategy" m="The company chooses what to pursue and what to reject"/><div className="strategyGrid"><div className="card strategyMain"><div className="eyebrow">Current company goal</div><h2>Turn available capital into durable recurring revenue</h2>{[['01','Discover','Research markets and identify opportunities.'],['02','Validate','Run simulations and customer tests.'],['03','Allocate','Move capital toward the highest expected return.'],['04','Learn','Measure outcomes and update the next plan.']].map(x=><div className="step" key={x[0]}><b>{x[0]}</b><div><strong>{x[1]}</strong><span>{x[2]}</span></div></div>)}</div><div className="card priorities"><div className="sectionTitle">CEO priorities</div>{[['Recurring revenue',92],['Capital preservation',87],['Market expansion',71],['Automation',96]].map(x=><div className="priority" key={x[0]}><span>{x[0]}</span><b>{x[1]}%</b><div className="bar"><i style={{width:x[1]+'%'}}/></div></div>)}</div></div></>}
function Memory(){return <><Panel t="Company Memory" m="Decisions and lessons become organizational knowledge"/><div className="memoryGrid">{[['Pricing lesson','Enterprise buyers accepted annual contracts when onboarding was included.'],['Trading lesson','Momentum strategy performs poorly during high-volatility reversals.'],['Sales lesson','Qualified leads convert better when the product agent prepares a custom demo.'],['Operations lesson','Automating onboarding reduced manual work by 41%.']].map(x=><div className="card memoryItem" key={x[0]}><div className="memoryDot"/><div><strong>{x[0]}</strong><p>{x[1]}</p><small>Learned by company memory · cycle 37</small></div></div>)}</div></>}
function SettingsView(){return <><Panel t="System Settings" m="Controls for simulation, agents, risk and integrations"/><div className="settingsList">{[['Autonomous simulation','ON'],['Real-money execution','OFF'],['Agent self-learning','ON'],['External integrations','SANDBOX'],['Maximum simulated loss','€2,000']].map(x=><div className="setting" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></>}
function Drawer({id,close}:{id:PersonId,close:()=>void}){const p=people.find(x=>x[0]===id)||people[0];return <div className="drawerBackdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><div className="agentAvatar large">{p[0]}</div><div className="eyebrow">{p[2]}</div><h2>{p[1]}</h2><div className="drawerStatus"><i className="dot"/> Working</div><div className="drawerBlock"><small>Current objective</small><p>{p[3]}</p></div><div className="drawerBlock"><small>Performance</small><p>{p[4]} success score</p></div><div className="drawerBlock"><small>Decision</small><p>Continue task, evaluate result and report to CEO.</p></div></aside></div>}
function Panel({t,m}:{t:string,m:string}){return <div className="panelTitle"><div><div className="eyebrow">AI Company OS</div><h1>{t}</h1><p>{m}</p></div><span className="pill">LIVE SIMULATION</span></div>}
function Head({title,meta}:{title:string,meta:string}){return <div className="sectionHead"><div><div className="sectionTitle">{title}</div><div className="sectionMeta">{meta}</div></div></div>}
function Stat({l,v,t}:{l:string,v:string,t:string}){return <div className="card stat"><div className="statLabel">{l}</div><div className="statValue">{v}</div><div className="trend">{t}</div></div>}
function Stage({n,c}:{n:string,c:string}){return <div className="stage"><div className="stageName">{n}</div><div className="stageCount">{c}</div></div>}
function Agent({x,work,open}:{x:string,work?:boolean,open?:()=>void}){return <button onClick={open} className={`agent ${work?'working':''}`}>{x}</button>}
function Metric({title,v,d}:{title:string,v:string,d:string}){return <div className="card metricCard"><div><small>{title}</small><strong>{v}</strong><span>{d}</span></div></div>}
