import Link from 'next/link';
import { Activity, ArrowLeft, Bot, CheckCircle2, GitBranch, ShieldCheck, Target, Timer, Zap } from 'lucide-react';
import '../../company.css';
import './task-detail.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].flatMap(companyId=>['T-1041','T-1042','T-1043','T-1044','T-1045','T-1046'].map(taskId=>({companyId,taskId})))}
const tasks:Record<string,{title:string;agent:string;status:string;dependency:string;priority:string;progress:number;result:string;next:string}>={'T-1041':{title:'Validate pricing experiment #41',agent:'Product Agent',status:'EXECUTING',dependency:'Research signal #88',priority:'HIGH',progress:76,result:'Pricing hypothesis is passing the evaluation gate.',next:'Compare conversion against baseline.'},'T-1042':{title:'Prepare landing page release',agent:'Product Agent',status:'EXECUTING',dependency:'T-1041',priority:'HIGH',progress:58,result:'Release candidate is being prepared.',next:'Publish after pricing validation.'},'T-1043':{title:'Analyze high-intent customer segments',agent:'Research Agent',status:'OBSERVING',dependency:'None',priority:'HIGH',progress:81,result:'Three-seat accounts remain the strongest expansion segment.',next:'Publish segment signal to CEO.'},'T-1044':{title:'Review weekly cash allocation',agent:'CFO Agent',status:'PLANNING',dependency:'T-1041',priority:'MEDIUM',progress:34,result:'Budget impact is being modeled.',next:'Approve or reject allocation.'},'T-1045':{title:'Run retention experiment',agent:'Sales Agent',status:'BACKLOG',dependency:'T-1043',priority:'MEDIUM',progress:12,result:'Waiting for customer segment signal.',next:'Start experiment after dependency completes.'},'T-1046':{title:'Publish experiment result',agent:'CEO Agent',status:'WAITING',dependency:'T-1041',priority:'HIGH',progress:5,result:'Blocked until experiment #41 is evaluated.',next:'Review Product Agent result.'}};
export default function TaskDetail({params}:{params:{companyId:string;taskId:string}}){const p=params;const t=tasks[p.taskId]||tasks['T-1041'];return <main className="companyOS"><aside className="companySide"><div className="companyBrand"><div className="companyMark">AI</div><div><b>AI Company OS</b><small>COMPANY OPERATING SYSTEM</small></div></div><Link className="portfolioBack" href={`/company/${p.companyId}`}>← <span>Company workspace</span></Link><div className="companyIdentity"><span>TASK {p.taskId}</span><strong>{t.title}</strong><small>{t.agent}</small><i><em/> {t.status}</i></div><div className="companySafety"><ShieldCheck size={15}/><span>Simulation mode<br/><b>Controlled task</b></span></div></aside><section className="companyMain"><header className="companyTop"><div><span className="companyEyebrow">TASK DETAIL / {p.taskId}</span><h1>{t.title}</h1><p>Execution state, dependency, owner, progress and result.</p></div><Link href={`/company/${p.companyId}`} className="detailBack"><ArrowLeft size={15}/> Back</Link></header><section className="taskDetailHero"><div><div className="detailIcon"><Zap size={25}/></div><span>{t.agent} · PRIORITY {t.priority}</span><h2>{t.result}</h2><b className="taskState"><i/>{t.status}</b></div><div className="taskScore"><strong>{t.progress}%</strong><span>PROGRESS</span></div></section><div className="detailStats"><DetailStat icon={<Target size={17}/>} label="Progress" value={`${t.progress}%`} detail="Execution"/><DetailStat icon={<Bot size={17}/>} label="Agent" value={t.agent.replace(' Agent','')} detail="Owner"/><DetailStat icon={<GitBranch size={17}/>} label="Dependency" value={t.dependency==='None'?'NONE':t.dependency} detail="Queue relation"/><DetailStat icon={<Timer size={17}/>} label="Priority" value={t.priority} detail="Current"/></div><div className="detailGrid"><section className="detailPanel"><Head icon={<Activity size={16}/>} title="Execution progress"/><div className="detailProgress"><i style={{width:`${t.progress}%`}}/></div><p>{t.result}</p><small>Next action: {t.next}</small></section><section className="detailPanel"><Head icon={<GitBranch size={16}/>} title="Dependency"/><h3>{t.dependency}</h3><p>{t.dependency==='None'?'This task can execute independently.':'This task is waiting for the dependency result before completing.'}</p></section><section className="detailPanel wide"><Head icon={<CheckCircle2 size={16}/>} title="Execution history"/><div className="historyRows"><History title="Task registered in autonomous queue" result="Accepted" time="Today"/><History title="Agent evaluated current state" result={t.status} time="6 min ago"/><History title="Result published to company runtime" result="Available for next decision" time="2 min ago"/></div></section></div><footer>AI Company OS · TASK → AGENT → DEPENDENCY → EXECUTION → RESULT</footer></section></main>}
function DetailStat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="detailStat"><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>}
function Head({icon,title}:{icon:React.ReactNode;title:string}){return <div className="detailHead">{icon}<h3>{title}</h3></div>}
function History({title,result,time}:{title:string;result:string;time:string}){return <div className="historyRow"><span className="historyDot"/><div><strong>{title}</strong><small>{result}</small></div><time>{time}</time></div>}
