'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowLeft, Bot, BrainCircuit, Building2, CircleDollarSign, Gauge, Network, ShieldCheck, Target, Users, Zap } from 'lucide-react'
import './tenant.css'

type Tenant={id:string;name:string;sector:string;market:string;operatingModel:string;objective:string;health:number;agents:string[];modules:string[];portal:string;createdAt:string;missions?:unknown[];tasks?:unknown[];knowledge?:unknown[]}
const agentNames:Record<string,string>={ceo:'CEO',research:'Research',product:'Product',sales:'Sales',cfo:'Finance'}
const cards=[
 ['agents',Bot,'AI Workforce','Core autonomous agents'],['missions',Target,'Missions','Define strategic missions'],['tasks',Zap,'Tasks','Control the execution queue'],['finance',CircleDollarSign,'Finance','Monitor company economics'],['knowledge',BrainCircuit,'Knowledge','Build company memory'],['operations',Network,'Operations','Run the autonomous loop'],['security',ShieldCheck,'Security','Policies and controls'],['portal',Users,'Client Portal','Client-facing operating view']
] as const
export default function TenantDashboard(){
 const [tenant,setTenant]=useState<Tenant|null>(null);const [missing,setMissing]=useState(false)
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('id');try{const list=JSON.parse(localStorage.getItem('ai-company-os-tenants')||'[]');const found=list.find((x:Tenant)=>x.id===id);found?setTenant(found):setMissing(true)}catch{setMissing(true)}},[])
 if(!tenant&&!missing)return <main className="tenantPage"><div className="tenantLoading">Loading tenant...</div></main>
 if(!tenant)return <main className="tenantPage"><div className="tenantEmpty"><Building2 size={30}/><h1>Tenant not found</h1><p>The requested provisioned company is not available in this browser session.</p><Link href="/master">Back to Master</Link></div></main>
 const count=(key:keyof Tenant)=>(tenant[key] as unknown[]|undefined)?.length||0
 return <main className="tenantPage"><header className="tenantHeader"><div><Link className="tenantBack" href="/master"><ArrowLeft size={15}/> Master Control</Link><span className="tenantEyebrow">TENANT CONTROL CENTER / PROVISIONED</span><h1>{tenant.name}</h1><p>{tenant.sector} · {tenant.market} · {tenant.operatingModel}</p></div><span className="tenantStatus"><i/> BUILDING</span></header><section className="tenantHero"><div><span className="tenantLabel">STRATEGIC OBJECTIVE</span><h2>{tenant.objective}</h2><p>The autonomous company foundation is provisioned. Configure missions, agents and operating policies before activation.</p></div><div className="tenantHealth"><Gauge size={19}/><strong>{tenant.health}%</strong><span>System health</span></div></section><section className="tenantStats"><div><span>Agents</span><strong>{tenant.agents.length}</strong></div><div><span>Modules</span><strong>{tenant.modules.length}</strong></div><div><span>Missions</span><strong>{count('missions')}</strong></div><div><span>Tasks</span><strong>{count('tasks')}</strong></div></section><section className="tenantGrid">{cards.map(([id,Icon,title,text])=><Link className="tenantCard" key={id} href={`/master/tenant/module?tenant=${encodeURIComponent(tenant.id)}&module=${id}`}><div className="tenantCardIcon"><Icon size={18}/></div><span>{title}</span><strong>{id==='missions'?`${count('missions')} configured`:id==='tasks'?`${count('tasks')} queued`:id==='knowledge'?`${count('knowledge')} memories`:id==='agents'?`${tenant.agents.length} agents`:id==='finance'?'Financial control':id==='portal'?'Private':'Ready'}</strong><p>{text}</p><small>Open module →</small></Link>)}</section><section className="tenantAgents"><div><span className="tenantLabel">AI WORKFORCE</span><h2>Core agents</h2></div><div className="agentPills">{tenant.agents.map(id=><span key={id}><Bot size={14}/>{agentNames[id]||id}</span>)}</div></section><footer className="tenantFooter"><span>Tenant ID: {tenant.id}</span><span>Created {new Date(tenant.createdAt).toLocaleString()}</span></footer></main>}
