'use client'

import { FormEvent, useState } from 'react'
import { ArrowRight, Building2, LockKeyhole, Mail, UserRound } from 'lucide-react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import '../login/auth.css'

export default function Signup(){
 const router=useRouter(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [company,setCompany]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent){e.preventDefault();setError('');if(name.trim().length<2||!email||password.length<12||company.trim().length<2){setError('Complete all fields. Password must contain at least 12 characters.');return}setBusy(true);try{const res=await fetch('/api/auth/signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,email,password,company})});const data=await res.json();if(!res.ok){setError(data.error==='ACCOUNT_EXISTS'?'An account already exists for this email.':'Unable to create the account.');return}localStorage.setItem('aicos-onboarding-company',company.trim());router.push('/dash-1')}catch{setError('Authentication service unavailable.')}finally{setBusy(false)}}
 return <main className="authShell"><div className="authVisual"><div className="authBrand"><span>AI</span><div><b>AI Company OS</b><small>AUTONOMOUS COMPANY</small></div></div><div className="authOrb"><div><Building2 size={28}/><b>CREATE YOUR OS</b><small>DASH 1 OWNER</small></div></div><p>Create the OWNER account that controls your global company operating system.</p></div><section className="authPanel"><div className="authCard"><div className="mobileBrand">AI COMPANY OS</div><div className="authEyebrow">CREATE OWNER ACCOUNT</div><h1>Build your company.</h1><p className="authLead">Your first account becomes the global OWNER of DASH 1.</p><form onSubmit={submit}><label>Your name<div className="inputWrap"><UserRound size={16}/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div></label><label>Work email<div className="inputWrap"><Mail size={16}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></div></label><label>Company name<div className="inputWrap"><Building2 size={16}/><input required value={company} onChange={e=>setCompany(e.target.value)} placeholder="Your company"/></div></label><label>Password<div className="inputWrap"><LockKeyhole size={16}/><input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 12 characters"/></div></label>{error&&<div className="formError">{error}</div>}<button className="primaryAuth" disabled={busy}>{busy?'Creating…':'Create OWNER account'} <ArrowRight size={16}/></button></form><p className="authLead" style={{marginTop:18}}>Already have an account? <Link href="/login">Sign in</Link></p></div><Link className="backLink" href="/welcome">← Back to introduction</Link></section></main>
}