'use client'

import { FormEvent, useState } from 'react'
import { ArrowRight, Building2, LockKeyhole, Mail, UserRound } from 'lucide-react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import '../login/auth.css'

export default function Signup(){
 const router=useRouter(); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [company,setCompany]=useState(''); const [error,setError]=useState('')
 function submit(e:FormEvent){e.preventDefault();if(name.trim().length<2||!email||password.length<6||company.trim().length<2){setError('Complete all fields. Password must contain at least 6 characters.');return}localStorage.setItem('aicos-account',JSON.stringify({name,email,company,createdAt:new Date().toISOString()}));localStorage.setItem('aicos-session',JSON.stringify({email,name,signedInAt:new Date().toISOString(),mode:'simulation'}));router.push('/portfolio')}
 return <main className="authShell"><div className="authVisual"><div className="authBrand"><span>AI</span><div><b>AI Company OS</b><small>AUTONOMOUS COMPANY</small></div></div><div className="authOrb"><div><Building2 size={28}/><b>CREATE YOUR OS</b><small>READY TO OPERATE</small></div></div><p>Create your account, establish your first company and start building an autonomous operating system.</p></div><section className="authPanel"><div className="authCard"><div className="mobileBrand">AI COMPANY OS</div><div className="authEyebrow">CREATE ACCOUNT</div><h1>Build your company.</h1><p className="authLead">Start with a secure workspace. You can configure agents and operations after onboarding.</p><form onSubmit={submit}><label>Your name<div className="inputWrap"><UserRound size={16}/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div></label><label>Work email<div className="inputWrap"><Mail size={16}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></div></label><label>Company name<div className="inputWrap"><Building2 size={16}/><input required value={company} onChange={e=>setCompany(e.target.value)} placeholder="Acme AI"/></div></label><label>Password<div className="inputWrap"><LockKeyhole size={16}/><input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></div></label>{error&&<div className="formError">{error}</div>}<button className="primaryAuth">Create workspace <ArrowRight size={16}/></button></form><p className="authLead" style={{marginTop:18}}>Already have an account? <Link href="/login">Sign in</Link></p></div><Link className="backLink" href="/welcome">← Back to introduction</Link></section></main>
}
