'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BarChart3, Bot, Check, ChevronRight, CircleDollarSign, Clock3, FileText, Globe2, Instagram, MessageSquare, Plus, Send, Settings, ShieldCheck, ShoppingBag, Sparkles, Target, TrendingUp, Wallet, X, Zap } from 'lucide-react';
import './company.css';

type Company={id:string;name:string;type:string;revenue:string;profit:string;agents:number;missions:number;growth:string;health:number;status:string};
const defaults:Company[]=[
{id:'alpha',name:'Company Alpha',type:'AI SaaS Platform',revenue:'€38,420',profit:'€12,840',agents:18,missions:4,growth:'+18.6%',health:94,status:'RUNNING'},
{id:'beta',name:'Company Beta',type:'AI Commerce',revenue:'€21,830',profit:'€7,420',agents:11,missions:3,growth:'+31.2%',health:91,status:'RUNNING'},
{id:'gamma',name:'Company Gamma',type:'AI Automation',revenue:'€4,280',profit:'€920',agents:7,missions:2,growth:'+42.8%',health:87,status:'BUILDING'}];
const cafeteria:Company={id:'cafeteria-madrid-centro',name:'Cafetería Madrid Centro',type:'Cafetería · Demo Client',revenue:'€42,300',profit:'€12,840',agents:7,missions:3,growth:'+18.4%',health:96,status:'RUNNING'};
const agents=[['AI CEO','Strategy & orchestration','ONLINE'],['Marketing Agent','Campaigns & content','READY'],['Sales Agent','Sales & customer analysis','ONLINE'],['Finance Agent','Cash flow & profitability','ONLINE'],['Operations Agent','Daily operations','ONLINE'],['Inventory Agent','Stock & purchasing','READY'],['Customer Agent','Reviews & support','ONLINE']];
const integrations=[['Instagram','CONNECTED'],['Facebook','CONNECTED'],['Google Business','CONNECTED'],['Google Ads','CONNECTED'],['WhatsApp Business','CONNECTED'],['TikTok','NOT CONNECTED'],['POS / Sales','NOT CONNECTED'],['Google Drive','CONNECTED']];
const initialMessages=[{role:'ai',text:'Olá. Sou o AI CEO desta empresa. Posso analisar o negócio, criar campanhas, acompanhar vendas e coordenar os agentes. O que você quer alcançar hoje?'}];
export default function CompanyPage(){
 const[company,setCompany]=useState<Company>(cafeteria); const[messages,setMessages]=useState(initialMessages); const[input,setInput]=useState(''); const[active,setActive]=useState('overview'); const[showConnections,setShowConnections]=useState(false); const[approvals,setApprovals]=useState([{id:1,title:'Campanha Café da Tarde',detail:'Meta Ads · €105 · 7 dias',type:'MARKETING'},{id:2,title:'Compra de café premium',detail:'Fornecedor · €240',type:'INVENTORY'}]);
 useEffect(()=>{try{const params=new URLSearchParams(window.location.search);const id=params.get('company');const raw=localStorage.getItem('aicos-companies');const list=raw?JSON.parse(raw):[];const found=[cafeteria,...defaults,...list].find((c:Company)=>c.id===id);if(found)setCompany(found)}catch{}},[]);
 const nav=[['overview','Overview'],['ai','AI CEO'],['marketing','Marketing'],['sales','Vendas'],['finance','Finanças'],['operations','Operações'],['agents','Agentes'],['integrations','Integrações'],['approvals','Aprovações']];
 function send(){const text=input.trim();if(!text)return;setMessages(m=>[...m,{role:'user',text},{role:'ai',text:reply(text)}]);setInput('')}
 function reply(text:string){const t=text.toLowerCase();if(t.includes('public')||t.includes('campanha')||t.includes('instagram')||t.includes('anúncio'))return 'Vou tratar isso como uma missão de Marketing. Analisei o objetivo, preparei uma campanha Café da Tarde, selecionei Instagram + Facebook e deixei o orçamento em €15/dia. A campanha está pronta para aprovação. Nenhuma publicação real é feita nesta demonstração.';if(t.includes('venda')||t.includes('vendas'))return 'As vendas estão 18,4% acima da referência. O maior espaço de crescimento está entre 16h e 19h. Recomendo testar uma campanha de Café da Tarde e acompanhar o ticket médio.';if(t.includes('estoque')||t.includes('stock'))return 'O Inventory Agent encontrou duas categorias que precisam de atenção. Posso preparar uma ordem de compra e enviar para aprovação antes de qualquer execução.';return 'Entendi. Vou decompor esse objetivo em tarefas para os agentes, verificar os dados disponíveis e trazer uma recomendação com próximos passos. Neste protótipo, ações externas sempre passam por aprovação.'}
 return <main className="companyShell"><aside className="companySidebar"><div className="companyLogo"><span>AI</span><div><b>AI COMPANY OS</b><small>CLIENT COMMAND</small></div></div><div className="companyIdentity"><div className="companyAvatar">CM</div><div><b>{company.name}</b><small>{company.type}</small></div></div><nav>{nav.map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>{setActive(id);if(id==='integrations')setShowConnections(true)}}>{id==='overview'?<BarChart3 size={15}/>:id==='ai'?<Sparkles size={15}/>:id==='marketing'?<Globe2 size={15}/>:id==='sales'?<ShoppingBag size={15}/>:id==='finance'?<Wallet size={15}/>:id==='operations'?<Zap size={15}/>:id==='agents'?<Bot size={15}/>:id==='integrations'?<Settings size={15}/>:<ShieldCheck size={15}/>}<span>{label}</span>{id==='approvals'&&approvals.length>0&&<i>{approvals.length}</i>}</button>)}</nav><div className="sidebarBottom"><div className="secure"><ShieldCheck size={14}/><span>Company isolated<br/><b>Secure tenant</b></span></div><Link href="/portfolio">← Master Portfolio</Link></div></aside><section className="companyMain"><header className="companyHeader"><div><span className="eyebrow">AUTONOMOUS COMPANY / LIVE</span><h1>{company.name}</h1><p>Seu negócio tem uma equipe de agentes trabalhando sob suas regras.</p></div><div className="headerActions"><span className="online"><i/> SYSTEM ONLINE</span><button><Settings size={15}/> Settings</button></div></header><section className="companyContent">
 {active==='overview'&&<Overview company={company} setActive={setActive}/>} 
 {active==='ai'&&<AiView messages={messages} input={input} setInput={setInput} send={send}/>} 
 {active==='marketing'&&<Marketing setActive={setActive}/>} 
 {active==='sales'&&<Placeholder title="Vendas" icon={<ShoppingBag/>} text="O Sales Agent analisa vendas, ticket médio, clientes e oportunidades."/>}
 {active==='finance'&&<Placeholder title="Finanças" icon={<CircleDollarSign/>} text="Fluxo de caixa, margem, custos e previsões ficam centralizados aqui."/>}
 {active==='operations'&&<Placeholder title="Operações" icon={<Zap/>} text="Os agentes acompanham tarefas, rotinas e exceções operacionais."/>}
 {active==='agents'&&<Agents/>}
 {active==='integrations'&&<Integrations onConnect={()=>setShowConnections(true)}/>} 
 {active==='approvals'&&<Approvals approvals={approvals} setApprovals={setApprovals}/>} 
 </section></section>{showConnections&&<ConnectionsModal onClose={()=>setShowConnections(false)}/>}</main>}
function Overview({company,setActive}:{company:Company;setActive:(s:string)=>void}){return <><div className="heroCommand"><div><span className="eyebrow">AI CEO</span><h2>O que você quer<br/><em>fazer hoje?</em></h2><p>Peça à IA para analisar, planejar e preparar ações para sua empresa.</p><button onClick={()=>setActive('ai')}>Falar com AI CEO <ArrowRight size={16}/></button></div><div className="commandOrb"><div><Sparkles size={22}/><b>7 AGENTS</b><small>WORKING FOR YOU</small></div></div></div><div className="kpis"><Kpi label="Receita este mês" value={company.revenue} delta="+18.4%" icon={<CircleDollarSign/>}/><Kpi label="Lucro" value={company.profit} delta="+12.1%" icon={<TrendingUp/>}/><Kpi label="Clientes" value="1,284" delta="+9.8%" icon={<ShoppingBag/>}/><Kpi label="Ticket médio" value="€8.42" delta="+4.6%" icon={<BarChart3/>}/></div><div className="overviewGrid"><div className="panel"><div className="panelHead"><div><span>ACTIVE MISSIONS</span><h3>O que os agentes estão fazendo</h3></div><button onClick={()=>setActive('agents')}>Ver agentes <ChevronRight size={14}/></button></div><Mission title="Analisar vendas da última semana" agent="Sales Agent" status="RUNNING" progress={78}/><Mission title="Preparar campanha Café da Tarde" agent="Marketing Agent" status="APPROVAL" progress={100}/><Mission title="Monitorar estoque de café" agent="Inventory Agent" status="RUNNING" progress={46}/></div><div className="panel activity"><div className="panelHead"><div><span>LIVE ACTIVITY</span><h3>Empresa em movimento</h3></div></div>{['Sales Agent analisou 1.284 clientes','Marketing Agent preparou nova campanha','Finance Agent atualizou margem','AI CEO identificou oportunidade de crescimento'].map((x,i)=><div className="activityRow" key={x}><i/><div><b>{x}</b><small>{i+2} min atrás</small></div></div>)}</div></div></>}
function Kpi({label,value,delta,icon}:{label:string;value:string;delta:string;icon:React.ReactNode}){return <div className="kpi"><div className="kpiIcon">{icon}</div><small>{label}</small><b>{value}</b><span>{delta}</span></div>}
function Mission({title,agent,status,progress}:{title:string;agent:string;status:string;progress:number}){return <div className="mission"><div className="missionIcon"><Bot size={16}/></div><div className="missionBody"><b>{title}</b><small>{agent} · {status}</small><div className="progress"><i style={{width:`${progress}%`}}/></div></div><strong>{progress}%</strong></div>}
function AiView({messages,input,setInput,send}:{messages:{role:string;text:string}[];input:string;setInput:(s:string)=>void;send:()=>void}){return <div className="aiPage"><div className="aiIntro"><span className="eyebrow">AI CEO / COMPANY INTELLIGENCE</span><h2>Fale com a empresa.</h2><p>Peça análises, estratégias ou ações. O AI CEO coordena os agentes e respeita suas regras de aprovação.</p></div><div className="chatBox"><div className="chatMessages">{messages.map((m,i)=><div className={`chatMessage ${m.role}`} key={i}><div className="chatAvatar">{m.role==='ai'?<Sparkles size={15}/>:<span>CM</span>}</div><div><small>{m.role==='ai'?'AI CEO':'VOCÊ'}</small><p>{m.text}</p></div></div>)}</div><div className="suggestions"><button onClick={()=>setInput('Crie uma publicidade para aumentar as vendas à tarde')}>Criar publicidade</button><button onClick={()=>setInput('Como estão minhas vendas?')}>Analisar vendas</button><button onClick={()=>setInput('Analise meu estoque')}>Analisar estoque</button></div><div className="chatInput"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Diga à IA o que você quer fazer..."/><button onClick={send}><Send size={16}/></button></div></div></div>}
function Marketing({setActive}:{setActive:(s:string)=>void}){return <div className="featurePage"><div className="featureTop"><div><span className="eyebrow">MARKETING AGENT</span><h2>Transforme uma ideia em campanha.</h2><p>A IA cria estratégia, copy e plano de mídia. A publicação real só acontece depois da aprovação.</p></div><button onClick={()=>setActive('ai')}>Pedir à IA <Sparkles size={15}/></button></div><div className="campaignCard"><div className="campaignPreview"><span>INSTAGRAM AD</span><div className="mockCreative"><b>CAFÉ DA TARDE</b><strong>☕ PAUSA PARA O CAFÉ?</strong><small>Venha experimentar nosso café da tarde.</small><em>MADRID CENTRO</em></div></div><div className="campaignDetails"><span className="statusTag">READY FOR APPROVAL</span><h3>Campanha Café da Tarde</h3><p>Objetivo: aumentar visitas entre 16h e 19h.</p><div className="detailGrid"><div><small>ORÇAMENTO</small><b>€15/dia</b></div><div><small>DURAÇÃO</small><b>7 dias</b></div><div><small>PÚBLICO</small><b>5 km</b></div><div><small>CANAIS</small><b>Meta</b></div></div><div className="campaignActions"><button className="approve" onClick={()=>alert('Demonstração: campanha aprovada. Em produção, o Advertising Agent enviaria a execução para a API autorizada.') }><Check size={15}/> Aprovar e publicar</button><button className="edit">Editar campanha</button></div></div></div></div>}
function Agents(){return <div className="featurePage"><span className="eyebrow">AI WORKFORCE</span><h2>Agentes trabalhando para você.</h2><p className="pageLead">Cada agente possui função, ferramentas e permissões próprias.</p><div className="agentGrid">{agents.map(a=><div className="agentCard" key={a[0]}><div className="agentIcon"><Bot size={18}/></div><div><b>{a[0]}</b><small>{a[1]}</small></div><span className="agentStatus"><i/> {a[2]}</span></div>)}</div></div>}
function Integrations({onConnect}:{onConnect:()=>void}){return <div className="featurePage"><div className="featureTop"><div><span className="eyebrow">CONNECTION CENTER</span><h2>As contas da empresa.</h2><p>Conecte serviços da própria empresa. A plataforma usa autorização oficial quando disponível e nunca precisa conhecer sua senha.</p></div></div><div className="integrationGrid">{integrations.map(x=><div className="integrationCard" key={x[0]}><div className="integrationIcon"><Globe2 size={17}/></div><div><b>{x[0]}</b><small>{x[1]==='CONNECTED'?'Autorização ativa':'Pronto para conectar'}</small></div><button onClick={onConnect}>{x[1]==='CONNECTED'?'Gerenciar':'Conectar'}</button></div>)}</div></div>}
function Approvals({approvals,setApprovals}:{approvals:{id:number;title:string;detail:string;type:string}[];setApprovals:(a:{id:number;title:string;detail:string;type:string}[])=>void}){return <div className="featurePage"><span className="eyebrow">HUMAN CONTROL</span><h2>Aprovações pendentes.</h2><p className="pageLead">A empresa pode trabalhar sozinha, mas ações sensíveis continuam sob seu controle.</p><div className="approvalList">{approvals.length===0?<div className="emptyState"><Check size={22}/>Nenhuma aprovação pendente.</div>:approvals.map(a=><div className="approvalCard" key={a.id}><div className="approvalIcon"><ShieldCheck size={18}/></div><div><span>{a.type}</span><b>{a.title}</b><small>{a.detail}</small></div><div className="approvalActions"><button className="approve" onClick={()=>setApprovals(approvals.filter(x=>x.id!==a.id))}>Aprovar</button><button onClick={()=>setApprovals(approvals.filter(x=>x.id!==a.id))}>Rejeitar</button></div></div>)}</div></div>}
function Placeholder({title,icon,text}:{title:string;icon:React.ReactNode;text:string}){return <div className="placeholder"><div>{icon}</div><span className="eyebrow">COMPANY MODULE</span><h2>{title}</h2><p>{text}</p><small>Este módulo está conectado à camada de agentes e será alimentado por dados reais quando as integrações forem ativadas.</small></div>}
function ConnectionsModal({onClose}:{onClose:()=>void}){return <div className="modalBackdrop"><div className="connectionModal"><button className="modalClose" onClick={onClose}><X size={18}/></button><span className="eyebrow">SECURE CONNECTION</span><h2>Conectar conta</h2><p>Na versão real, você será direcionado à página oficial do serviço para autorizar o AI Company OS. A senha não entra no nosso sistema.</p><div className="oauthMock"><Instagram size={18}/><div><b>Instagram / Meta</b><small>OAuth authorization</small></div><button onClick={onClose}>Autorizar</button></div><div className="oauthMock"><Globe2 size={18}/><div><b>Google Ads</b><small>OAuth authorization</small></div><button onClick={onClose}>Autorizar</button></div><div className="vaultNote"><ShieldCheck size={16}/> Tokens e segredos ficam protegidos no backend em produção.</div></div></div>}
