import Link from 'next/link';
import './portal.css';

export function generateStaticParams(){return ['alpha','beta','gamma'].map(companyId=>({companyId}))}
const companies:Record<string,{name:string;type:string;revenue:string;profit:string;health:string;agents:number;objective:string;status:string}>={
 alpha:{name:'Company Alpha',type:'AI SaaS Platform',revenue:'€38,420',profit:'€12,840',health:'94%',agents:18,objective:'Launch the next recurring-revenue product',status:'OPERATIONAL'},
 beta:{name:'Company Beta',type:'AI Commerce',revenue:'€21,830',profit:'€7,420',health:'91%',agents:11,objective:'Increase conversion and customer lifetime value',status:'OPERATIONAL'},
 gamma:{name:'Company Gamma',type:'AI Automation',revenue:'€4,280',profit:'€920',health:'87%',agents:7,objective:'Validate the first enterprise automation offer',status:'BUILDING'}
};
export default function ClientPortal({params}:{params:{companyId:string}}){const c=companies[params.companyId]||companies.alpha;return <main className="clientPortal"><header className="portalHeader"><Link href="/" className="portalBrand"><span>AI</span><div><b>AI Company OS</b><small>CLIENT PORTAL</small></div></Link><div className="portalStatus"><i/> {c.status}</div></header><section className="portalHero"><div><span className="portalEyebrow">{c.type}</span><h1>{c.name}</h1><p>Your company performance, AI workforce and active objectives in one controlled workspace.</p><Link href={`/company/${params.companyId}`} className="portalPrimary">Open company workspace →</Link></div><div className="healthOrb"><strong>{c.health}</strong><span>COMPANY HEALTH</span></div></section><section className="portalStats"><article><span>Revenue</span><b>{c.revenue}</b><small>Current cycle</small></article><article><span>Net profit</span><b>{c.profit}</b><small>Current cycle</small></article><article><span>AI workforce</span><b>{c.agents}</b><small>Agents operating</small></article><article><span>Status</span><b>{c.status}</b><small>Controlled runtime</small></article></section><section className="portalGrid"><article className="portalCard large"><span>ACTIVE OBJECTIVE</span><h2>{c.objective}</h2><div className="progress"><i style={{width:c.health}}/></div><small>Execution health aligned with the current operating policy.</small></article><article className="portalCard"><span>AI OPERATIONS</span><h3>Autonomous company loop</h3><p>Goal → Mission → Tasks → Agents → Results → Learning.</p><Link href={`/company/${params.companyId}?view=agents`}>View AI workforce →</Link></article><article className="portalCard"><span>INTELLIGENCE</span><h3>Decision layer</h3><p>Evidence-backed signals, forecasts and risk controls are continuously evaluated.</p><Link href={`/company/${params.companyId}?view=intelligence`}>View intelligence →</Link></article></section><footer>AI Company OS · Controlled client environment · Simulation-first execution</footer></main>}
